### ISSUE TITLE
Too abstracted from AWS SDK

### ISSUE THREAD

**Issue by mboudreau** [bbc/sqs-consumer#10]
Hi,

We're using sqs-consumer and it's working well for our nodejs microservice, but I feel that it's too abstracted from the AWS implementation, meaning that if we want to use other parameters in the receive function, we can't.  It should be closer to how [AWS allows us to do things](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#receiveMessage-property).  

As such, I've forked your code and added a new signature to the consumer function:
```
function Consumer(params, handler, sqs)
```
The first two parameters are required, while the last one is optional.  The params is an object to be used in the receive function, and the handler is simply a function to process the message, while the sqs argument is to set a custom SQS object if needed but defaults to `new AWS.SQS()` if none specified.

By using this implementation, the library gets to concentrate on what it does best, which is the polling mechanism, and let's the AWS sdk does what it does best.

I wanted to know if this is something that you would consider pulling back in.  If not, I would just create my own project since I don't want to spent the time rewriting the unit tests.

**Comment by mboudreau** [comment]
Another way to do this would be to have an object for setting the arguments, but have an sqsParams and sqsOptions to separate the AWS SDK specific information

**Comment by robinjmurphy** [comment]
Hi @mboudreau. Thanks for your feedback. Will take a look later today.

**Comment by robinjmurphy** [comment]
How does a `receiveMessageParams` property in the constructor options sound? It would replace the `batchSize` and `messageAttributeNames` options and we would merge it with the parameters configured by the library (which I think would be just `queueUrl`.)

This would mean that we don't have to reimplement, validate and document all of the options supported by the AWS client.

**Comment by mboudreau** [comment]
@robinjmurphy That's what I was thinking as well, but since most people would only use the queue Url and the messageHandler, we would need to simply it as much as possible.  Which is why I think it should be as simple as:
```
consumer.create({
    QueueUrl: 'https://sqs.us-east-1.amazonaws.com/some-id/some-queue'
})
.on('message', function(message, done){})
.on('error', function(err){});
```
The only parameter needed in the create is the params for `receiveMessage`.  I can add a second argument to the function for a custom SQS object so that the final signature of the function is `consumer.create({}, new AWS.SQS())`.

This will break the current implementation and would be a major version change, but I think it's the better approach.  I'll gladly create a PR if you agree.

**Comment by robinjmurphy** [comment]
Hi @mboudreau. Happy to make a breaking change, but I think my preference would be...

Basic usage:

```js
var app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: function (message, done) {}
});

app.on('error', function (err) {});
``` 

(This is the same as the existing API)

And then for users who want to specify the receive params:

```js
var app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: function (message, done) {},
  receiveMessageParams: {
    BatchSize: 20,
    AttributeNames: ['ApproximateFirstReceiveTimestamp'],
    WaitTime: 10
  }
});

app.on('error', function (err) {});
```

We have avoided using a `message` event because of the possibility of setting up multiple listeners.

**Comment by mboudreau** [comment]
I don't agree with it. QueueUrl is now in the consumer's params and can be
added to the receiveMessage params as well. This duplication is bound to
confuse many people.

I also don't agree with your assumption that having more than one message
handler is bad. This could be said the same for http data handler. Let the
user decide what to do.

If you don't agree, I'll have to fork this repo and create my own project.

**Comment by robinjmurphy** [comment]
When it comes to the `QueueUrl`, we would only ever send one value - we'd merge the values together, but the `receiveMessageParams` would take precedence.

I'm against the `message` event because it makes it all too easy for a user to get confused, in a way that a single function definition doesn't.

If you're happy to go with the `receiveMessageParams` option let me know, otherwise it looks like you want to follow a different approach.

**Comment by robinjmurphy** [comment]
Will close this as I haven't heard back. Re-open if you like the sound of the proposal above.
