### ISSUE TITLE
Sending messages larger than 256kb

### ISSUE THREAD

**Issue by mm739521** [bbc/sqs-consumer#100]
I'm working on a project where it's possible that messages being sent are larger than the sqs limits of 256kb.

I have found this solution https://github.com/awslabs/amazon-sqs-java-extended-client-lib for java but was wondering if there was any similar package for Node.js.

Thank you

**Comment by nspragg** [comment]
@mm739521 - When asking general questions about node packages, it's better to use technical forums. 

Try https://stackoverflow.com
