### ISSUE TITLE
SQS Msgs are not being deleted with done callback

### ISSUE THREAD

**Issue by chrislewispac** [bbc/sqs-consumer#102]
I am receiving messages over and over again. I spoke with AWS support who informed me.....

As discussed on chat, the most likely reason for this is due to the message delete has been called with an old message handle as described at this link - http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteMessage.html

**Comment by niklasR** [comment]
Hello @chrislewispac,
running sqs consumer in debug mode (setting ENV var `DEBUG=sqs-consumer` should do that) will show you the message ID for which the handle is passed to DeleteMessage.
