### ISSUE TITLE
message received and deleted from SQS but no handleMessage called

### ISSUE THREAD

**Issue by shokuie** [bbc/sqs-consumer#104]
sqsConsumer does not call anything (handleMessage or any of events) but messages are received and removed from sqs queue. Here is my code, any hints would be highly appreciated.

```
 function start (awsSqs) {
 log.debug('cunsumer started.');

 const consumer = sqsConsumer.create({
    queueUrl: config.moQueueUrl,
    messageAttributeNames: ['All'],
    waitTimeSeconds: config.msgWaitTime,
    sqs: awsSqs,
    handleMessage: (message, done) => {
      try {
        //I even simplified my handler to test
        log.info('Consumer DONE!');
        done();
      } catch (err) {
        log.warn('Exception on receiving the massage in Consumer : ', err);
        done(err);
      }
    }
  });

  consumer.on('error', (err) => {
    log.debug('errorrrrrrrr : ', err.message);
  });

  consumer.on('message_received', (message) => {
    log.info('message recieved event : ', JSON.stringify(message));
  });

  consumer.on('message_processed', (message) => {
    log.info('message processed : ', JSON.stringify(message));
  });

  consumer.on('processing_error', (err, message) => {
    log.info('message processing error : ', err, JSON.stringify(message));
  });

  consumer.start();
}
```

**Comment by nspragg** [comment]
@shokuie - using a modified version of the code you've provided (using the default AWS.SQS instance and replacing `log` with console), I'm not able to reproduce this. The messageHandler is successfully called and the messages are removed. 

If you are using a custom instance of AWS.SQS, ensure it's configured correctly.

**Comment by shokuie** [comment]
Thanks @nspragg , I'm working with AWS support to see if I can get who is getting messages. As I'm the only one confronting this issue most probably its something on my side and not sqsCosumer.

**Comment by emonhaider** [comment]
I am having a similar issue where it is intermittently deleting the message from SQS without processing it. In my case, handleMessage calls another method which returns a promise. Once the promise is resolved, done() is called. Is there any known issue with promise?

**Comment by kodayashi** [comment]
@emonhaider - Did you figure this out? I have the same issue (sometimes handleMessage is invoked and sometimes it is not, but messages are deleted from queues). I'm my handleMessage is async and I'm wondering if that's the issue...
