### ISSUE TITLE
How do you handle batch messages individually and call done()

### ISSUE THREAD

**Issue by jee-man** [bbc/sqs-consumer#107]
I am unsure how to invoke done/delete after processing a batch of messages. Currently invoking done deletes just one message and starts repolling. The event for responses handled doesn’t accept any arguments.

**Comment by niklasR** [comment]
The `handleMessage(message, done)` gets invoked _per message_ received, even in a batch scenario.

Calling done without an error will delete _that one message_, not the batch. If you could show how you use, that might help troubleshooting more easily.

**Comment by nspragg** [comment]
Issue looks stale - closing.
