### ISSUE TITLE
`undefined` queue name in error message

### ISSUE THREAD

**Issue by hrdwdmrbl** [bbc/sqs-consumer#109]
`error: SQS Error occured trying to interact with the queue:  undefined SQSError: SQS receive message failed: The specified queue does not exist for this wsdl version`

Not a big deal, the queue indeed does not exist so the root error is my own fault, but the error message is also a bit broken since it isn't logging the right queue name

**Comment by hrdwdmrbl** [comment]
Oups, my error!

**Comment by niklasR** [comment]
Thanks, will take a look soon!
