### ISSUE TITLE
Defaults for AttributeNames & MessageAttributeNames

### ISSUE THREAD

**Issue by mboudreau** [bbc/sqs-consumer#11]
Both should be set to ['All'] for simplicity.

**Comment by robinjmurphy** [comment]
Happy to do this if you want to submit a PR with the updated default, or do it as part of #10 if we change the constructor interface.

**Comment by robinjmurphy** [comment]
Closing this issue as the value can be set to `All` if required. I think the AWS default is to not include any attributes by default so we'll stick with that.

**Comment by jamietre** [comment]
Sorry to resurrect this from the dead, but I don't think it's accurate./
