### ISSUE TITLE
more batchSize emulation

### ISSUE THREAD

**Issue by ifubar** [bbc/sqs-consumer#110]
Is there a way to parallel fetch more then 10 messages?
Use case: i need to pull messages from the queue and push to another one. The current realization is waiting for i/o before fetch new batch of messages.

**Comment by landau** [comment]
It is not possible. I tried to add this feature in the past https://github.com/bbc/sqs-consumer/pull/73. I was pointed to use this as an alternative: https://github.com/TomFrost/Squiss

**Comment by nspragg** [comment]
@landau  - thanks.
