### ISSUE TITLE
Messages not being deleted when done() is invoked

### ISSUE THREAD

**Issue by Steague** [bbc/sqs-consumer#112]
I have a consumer looking for specific messages and calling done(); when they are found. Otherwise done(new Error()); is called. But my messages are just going to an In Flight status and not being deleted from the queue. Eventually they go back to Available status.

My queue is set for having messages deleted and received.

What am I doing wrong?

Below is my code which is 95% from the example given in the README:

```const Consumer = require('sqs-consumer');

const app = Consumer.create({
  queueUrl: '<my queue URL>',
  batchSize: 10,
  handleMessage: (message, done) => {
    var body = JSON.parse(message.Body);

    if (body &&
        body.type &&
        body.type == "new") {
        done();
        app.stop();
        console.log("Starting job", body.job);
        // do some work with `message`
        process.exit();
    } else {
        console.log("Not a new job", body);
        done(new Error("I only want new jobs"));
    }
  }
});

app.on('error', (err) => {
  console.log(err.message);
});

app.start();```

**Comment by nspragg** [comment]
If the messages are not being deleted it implies the `done` is not being called. Is the `.parse` call failing?

**Comment by Steague** [comment]
@nspragg the `console.log("Starting job", body.job);` line is being called and the process does exit. is there something you would suggest to verify the `done()` line is being called?

I have 4 "new job" messages in my queue, so it is correctly stopping/exiting after the 1st message

```
ubuntu@ip-172-31-34-175:~$ node job-handler.js
Starting job JOB-123
Done in 0.43s.
ubuntu@ip-172-31-34-175:~$
```

**Comment by Steague** [comment]
I think I found the problem.

When calling `process.exit()` too quickly (because of the async nature of the package) the node process ended before the delete call was made and thusly the message stayed in the queue.

Are there any plans to fire a callback or trigger a promise once the results from `done()` are returned? That way I would know the message handling was complete before terminating my process.
