### ISSUE TITLE
What is the default visibility timeout?

### ISSUE THREAD

**Issue by BelfordZ** [bbc/sqs-consumer#115]
is it the same as [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html), aka 30 seconds?

**Comment by scripter-co** [comment]
It is indeed. [There's no default defined](https://github.com/bbc/sqs-consumer/blob/035bc7dd084ff4fc824e69d75aa11495bc19e5fd/index.js#L47).

**Comment by BelfordZ** [comment]
Thx boss
