### ISSUE TITLE
Changing the visibility timeout of a message

### ISSUE THREAD

**Issue by jackphilippi** [bbc/sqs-consumer#116]
Is there a way to add a delay timer to a message ? In our use case, we want to try and process a message which may fail; If it fails, we want to double its timeout/delay, limited by a max value (eg. 400sec). Is this possible with sqs-consumer?

**Comment by pratikCse13** [comment]
how did you solve this @jackphilippi? I need to implement the same. Thanks!!

**Comment by jackphilippi** [comment]
Hi @pratikCse13 - your message must have been lost among all of my notifications. In case you're still wondering, we solved this by changing the message visibility exponentially via SQS and the node js AWS SDK:

```javascript
...
const visibilityChange: aws.SQS.ChangeMessageVisibilityRequest = {
    QueueUrl: queueUrl,
    ReceiptHandle: message.ReceiptHandle,
    VisibilityTimeout: newVisibilityTimeout,
};

this.sqs.changeMessageVisibility(visibilityChange, err => {
    if (err) {
        logger.error(`Encountered error when updating visibilityTimeout. Err: ${err} for Msg: ${message}`);
    }
});
...
```

Hopefully that helps ~
