### ISSUE TITLE
Consumer doesn't receive SQS QUEUE messages

### ISSUE THREAD

**Issue by naissa12** [bbc/sqs-consumer#117]
I'm using your plugin and sometimes when I poll the SQS queue, messages are not getting received.

Messages get added to the Queue but the Consumer does not seem to be receiving it.

Questions
- What configuration should I set on the AWS queue to work with the long polling of the consumer? What should the VisibilityTimeout be? the WaitTimeInSeconds?
- In what conditions does the Consumer not receive Queue messages? 
- What is the ideal configuration do you suggest that I set on the Consumer to make it work well?

**Comment by kevinrambaud** [comment]
Hi @naissa12 based on the [AWS documentation](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sqs-examples-enable-long-polling.html), you need to set the `ReceiveMessageWaitTimeSeconds` options between 1 to 20 to enable long polling. This link I provided give you examples of how to set it on a new or existing queue.

**Comment by nspragg** [comment]
Thanks @kevinrambaud
