### ISSUE TITLE
Considering to switch from callbacks to promises

### ISSUE THREAD

**Issue by kevinrambaud** [bbc/sqs-consumer#118]
Would you be open to receive a PR that contains a refactoring of the current implementation from callbacks to promises ?

Also, it would be great to update `handleMessage` option to make it use promise to be able to use async/await.

We could imagine going from 

```javascript
const app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: (message, done) => {
    // do some work with `message`
    done();
  }
});
```

to

```javascript
// using async/await with `handleMessage`

const app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: async message => {
    // do some work with `message`
  }
});
```

```javascript
// using promise with `handleMessage`
const app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage:  message => {
    // do some work with `message`
    return Promise.resolve();
  }
});
```

That would be a major version but hey, we are in 2018 and promises are the future :)

**Comment by nspragg** [comment]
Hi @kevinrambaud. Yes, we would accept a PR for switching to async functions - it's long overdue. I'll create an issue for this, providing the necessary details. I'll assign to you, if you're interested doing this work.

**Comment by kevinrambaud** [comment]
Sure, you can assign me to the new issue. I close this issue.
