### ISSUE TITLE
Pull in only SQS from aws-sdk

### ISSUE THREAD

**Issue by jpsear** [bbc/sqs-consumer#120]
The bundle size this module generates is quite large. I was wondering if it could reference the SQS API more precisely? 

This is untested, but I think we could do:

```js
const SQS = require('aws-sdk/clients/sqs');
```

Ref: https://github.com/aws/aws-sdk-js/blob/master/clients/sqs.js

Any thoughts?

**Comment by nspragg** [comment]
Hi @jpsear 

Are you looking to save memory? Have you profiled it? 

Technically, only requiring the SQS client and instantiating it directly should work.

**Comment by jpsear** [comment]
I'm looking to reduce bundle size. When I deploy — my whole project is uploaded to a CI server, where it is built. SQS pulls in the whole AWS SDK, when it could perhaps only pull in the SQS part.

I'm only pulling in sqs-consumer, but in turn — that pulls in the AWS SDK

**Comment by coxom** [comment]
@jpsear We used this strategy to avoid pulling the whole AWS:

https://github.com/hypercharge-code/sqs-consumer/blob/896cf87501f64ea48f1d9660fc04d8dc0c5ebdc7/index.js#L6

Also imported from the core for the config: 

```javascript
import AWS from 'aws-sdk/lib/core';
AWS.config.update({
    region: 'eu-west-1',
    accessKeyId: credentials.accessKeyId,
    secretAccessKey: credentials.secretKey,
    sessionToken: credentials.sessionToken
});
```

**Comment by coxom** [comment]
@jpsear agreed. Just waiting on @nspragg answer to your question. If there is interest we can create a PR.

**Comment by nspragg** [comment]
We'll consider this for the next release. Thanks.
