### ISSUE TITLE
Support for short polling

### ISSUE THREAD

**Issue by nwpointer** [bbc/sqs-consumer#121]
Is there any interest in supporting short polling? 

Currently if I call Consumer.create and pass in a options argument with waitTimeSeconds: 0 then waitTimeSeconds is ignored making it impossible to short poll.

I am happy to submit a pr if there is interest.

**Comment by nspragg** [comment]
@nwpointer  - thanks for the suggestion. We don't have any need for this at the moment, but certainly a consideration for a future release.
