### ISSUE TITLE
Need to detect dropped connections and reconnect

### ISSUE THREAD

**Issue by aaronpeterson** [bbc/sqs-consumer#122]
I'm passing my own instance of SQS to this library and I have set the httpOptions (see https://github.com/aws/aws-sdk-js/issues/367#issuecomment-56875656) -- I have tested this by connecting sqs-consumer successfully and then purposely dropping the connection (as happens we are finding quite often in various aws data centers).  We need to be able to recover from this situation.

One problem I have found is that my observation of 'error' which includes name "SQSError" and message "SQS receive message failed: Connection timed out after 25000ms" -- it does not seem safe to use a regular expression for "connection timed out" as this can change and is not part of your API.

Is there a way I can more precisely identify this specific error state?

Need to keep a queue worker working like queue workers work.

**Comment by dfdeagle47** [comment]
This issue is caused by https://github.com/bbc/sqs-consumer/blob/master/index.js#L98

```
if (err) {
  this.emit('error', new SQSError('SQS receive message failed: ' + err.message));
}
```

A new error is created with the message from the original error, so that's why you can't do much more than a regexp.

If you fork the repo and change the line to

```
if (err) {
  this.emit('error', err);
}
```

You should be able to do something that makes more sense like

```
app.on('error', (err) => {
  if (err.code === 'TimeoutError') {
    //Handle timeout error here
  }
});
```

**Comment by nspragg** [comment]
We'll consider incorporating this into our next release. Thanks.

**Comment by tgiachi** [comment]
Any updates? thank you!
