### ISSUE TITLE
support handle messages in batch

### ISSUE THREAD

**Issue by frsechet** [bbc/sqs-consumer#128]
Hi,

in some cases, it is perfectly fine to handle the messages in batch and not one by one. For example, in our scenario, each message in the queue requires to call an HTTP endpoint to process it. The HTTP endpoint supports batch handling, so instead of calling it 10 times, I could call it just once, which is a better use of resources (networking, parallelization and such).

Would you accept a PR that adds an option for `handleMessagesBatch`? I think it would be a great feature to be able to pick between "handle messages one by one" or "handle all messages at once".

What do you think?

**Comment by frsechet** [comment]
https://github.com/bbc/sqs-consumer/blob/ccdd3e839bb5eb37229b29f9774e52e9ef8f5a8f/index.js#L107-L113

If the user actively defined a batch method, use that, otherwise use the standard behaviour. It is opt-in and non-breaking.

**Comment by nspragg** [comment]
@frsechet - sounds good 👍

**Comment by Krypternite** [comment]
How long before this gets done ?

**Comment by nspragg** [comment]
released in `v5.3.0`.
