### ISSUE TITLE
Handler timeouts

### ISSUE THREAD

**Issue by nspragg** [bbc/sqs-consumer#136]
Consider adding a `timeout` to the `handler function`. Currently, it's possible for a function invocation to never complete. This can result in an instance of a consumer not being able to poll for messages if all handler functions stay in a running state (blocked). 

An optional timeout could be specified (non-breaking change). On timeout, the handler(s) would be released, allowing polling for new messages. A `timeout` event could be emitted.

**Comment by niklasR** [comment]
Makes sense 👍

**Comment by nspragg** [comment]
This may be related to #130

**Comment by nspragg** [comment]
@ShahidH - thanks for the update. This look like something that is worth investigating. Although this is related to timing out the `handler` I'm going to create a new issue for this.

**Comment by nspragg** [comment]
Fix released in v4.1.0
