### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by rkgrep** [bbc/sqs-consumer#144]
Could you, please, publish TS definitions to NPM as well?

**Comment by niklasR** [comment]
Will do when we release 4.2.0. Hopefully by end of this week.

**Comment by niklasR** [comment]
This is now released and published to npm tagged as `@beta`: https://www.npmjs.com/package/sqs-consumer/?activeTab=versions

**Comment by nspragg** [comment]
V5 has now been released.
