### ISSUE TITLE
Handle of errors (nack to sqs)

### ISSUE THREAD

**Issue by guyisra** [bbc/sqs-consumer#146]
in previous version before v4, after the logic of handleMessage, done() would be called to remove the message from sqs, and done(err) to not remove it and clear the visibility timeout for the message

Now, in version 4, there is no callback, so done() on successful handling doesn't need to be called.

What happens where there is an error?

**Comment by niklasR** [comment]
When there is an error, the error will be thrown. You can catch it using [the `try catch` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch).

The message does not get deleted, and the visibility timeout gets cleared.

So, same behaviour as before, without callbacks.

This is tested [here](https://github.com/bbc/sqs-consumer/blob/82b808e69a62ceb8fcea5f003275f28080af6dfe/test/consumer.ts#L459) and [here](https://github.com/bbc/sqs-consumer/blob/82b808e69a62ceb8fcea5f003275f28080af6dfe/test/consumer.ts#L330).
