### ISSUE TITLE
Possible memory leak in v5.0.0

### ISSUE THREAD

**Issue by johanarnor** [bbc/sqs-consumer#148]
### Description
I just updated from 3.8.0 -> 5.0.0 and experienced ever increasing memory usage. 

<img width="1197" alt="screenshot 2019-02-20 at 21 04 17" src="https://user-images.githubusercontent.com/3757533/53121072-a0edaf80-3553-11e9-890b-2687f1008e92.png">

The update was reverted with release `034d565f` with basically the following changes.

```diff
...
+ "sqs-consumer": "^3.8.0",
- "sqs-consumer": "^5.0.0",
...
```

```diff
+const Consumer = require('sqs-consumer')
-const { Consumer } = require('sqs-consumer')
...
```

```diff
+const handler = async (data, done) => {
-const handler = async (data) => {
  try {
      await doStuff(data)
  } catch (error) {
    // log error
+    return done(error)
-    throw error
  }
+  done()
}
```

### Steps to reproduce
Don't really have a good way to reproduce.

### Operating system
Running on a Standard-1X dyno in Heroku, node 8.14.1

**Comment by niklasR** [comment]
Hi @johanarnor,
Thanks for reporting this. We have not experienced issues with this on our end, but will investigate.

Couple of questions:
- `034d565f` is not a commit or release I can find [on github](https://github.com/bbc/sqs-consumer/commit/034d565f). What are you referring to with that string?
- The code changes you're outlining, is that detailing what you did in order to fix the memory leak on your side? There is no `handler` variable in this codebase.

If I understand correctly, this is the `handleMessage` function you pass to sqs-consumer with the memory leak occuring:
```js
const handler = async (data) => {
  try {
    await doStuff(data)
  } catch (error) {
    // log error
    throw error
  }
  done()
}
```
Where is `done` defined in this case?

**Comment by johanarnor** [comment]
Hi! First, thanks for the quick response.
- `034d565f` is just referring to the attached picture (we're using a private GitHub repo), i.e the commit/release that fixed the leak by reverting according to the diff.
- The done at the end was just a typo. It was put back when reverting to 3.8.0. I've updated the original post. 
- Yes, the diff is only what I changed in order to revert the upgrade. Our `app` stayed exactly the same (se below).
```js
const app = Consumer.create({
  queueUrl: process.env.SQS_QUEUE_URL,
  handleMessage: handler,
  batchSize: 10,
  visibilityTimeout: 60
})
```

**Comment by niklasR** [comment]
Okay, makes sense, thanks. I am not overly familiar with the Heroku interface.

It does look like we see some changes in pattern in memory usage, as well, but so far on our end it does seem to free up by itself without the machine falling over. We will do some comparisons between versions in runtime, and have a look at the code.

Any hints/ideas are welcome - will keep this release published for now until we can confirm an issue either way.

**Comment by johanarnor** [comment]
Thanks for looking into it. Don't have any hints or ideas though. Also, if you can't reproduce it, don't put too much effort into it. We have no problems using v3.8.0.

**Comment by niklasR** [comment]
I have a theory, which is addressed in #149:

In v3, only two functions depend on each/"await" the completion of a callback: `_handleSqsResponse` waits for `_processMessage` and its dependents to complete, and then loses the reference to that call of `_processMessage` and the circle begins anew, allowing for garbage collection of old invocations.

In v5, everything awaits everything - the very first call to `start` awaits for completion of `poll`, which awaits a new completion of `poll` when the message has been processed - and this goes on and on, so until there is an error. The very first call to `start` needs to keep a reference to the very first call of `poll` and all subsequent ones, therefore disallowing garbage collection of all invocations of `poll`.

In the PR, `poll` does not await `poll` anymore, but just "fires and forgets" a new call to `poll` when its own invocation completes, therefore allowing for garbage collection.

We'll test this, and discuss whether this makes sense. Will keep you updated.

**Comment by niklasR** [comment]
We have released this, tagged as `beta` on npm. We will test this now on our side - feel free to try it on your end. Install with `npm install sqs-consumer@beta`.

**Comment by niklasR** [comment]
After 3 hours of monitoring, v5.0.1 has shown an improvement in our memory graphs compared to v5.0.0.

Please try that out, and let us know if the issue still persists.

**Comment by johanarnor** [comment]
@niklasR Thanks for this! I've updated to v5.0.1 and can confirm that it solves my issue.

**Comment by tnolet** [comment]
@niklasR this is awesome. Had the same issue, thanks for the fix
