### ISSUE TITLE
Expose the `ConsumerOptions` type 

### ISSUE THREAD

**Issue by cadz7** [bbc/sqs-consumer#150]
Hello,

I'm currently writing some wrapper code around this library. 
In order to do so, my wrapper typescript code would need access to `ConsumerOptions` type. 

Would it be acceptable to expose it alongside the `Consumer`?

Thanks

**Comment by nspragg** [comment]
@cadz7 - Happy to accept a PR for this.

**Comment by nspragg** [comment]
release as 5.1.0
