### ISSUE TITLE
handleMessage called too infrequently

### ISSUE THREAD

**Issue by mlfarrell** [bbc/sqs-consumer#157]
I have 1000 messages in my queue.  Ideally I'd go through all of these in a matter of a second or two.  However SQS is delivering them to me roughly once per second.  Even at a batch of 10 at time, this is just too slow for my application.  Is this a limitation of what SQS can do?  i.e., am I misusing the service?

Please feel free to close if this is the intended behavior.

**Comment by nspragg** [comment]
@mlfarrell - We will be releasing a [batch message handler](https://github.com/bbc/sqs-consumer/issues/128) in v5.3.0. This may be of use to you and is expected to be released within the next week. 

`sqs-consumer` is intended to be used in light weight services (microservices)  where you can spin up multiple instances.

**Comment by mlfarrell** [comment]
Indeed I am using this for a microservice.  Thanks for the quick answer!
