### ISSUE TITLE
Add CHANGELOG.md file

### ISSUE THREAD

**Issue by lagay** [bbc/sqs-consumer#158]
I was trying to upgrade from v3.8.0 to v5.x and was unable to quickly figure out the difference; a change log would help. It would also be useful if the change log captured how to upgrade from one major version to the next major version; what are the differences and gotchas to look out for.
Thank you!

**Comment by niklasR** [comment]
Each release has its changes documented here: https://github.com/bbc/sqs-consumer/releases
