### ISSUE TITLE
Differentiate between internal and external events

### ISSUE THREAD

**Issue by owais** [bbc/sqs-consumer#16]
Is there a way to tell if an error was raised by client code (one of the message processing handlers) or by the library (sqs-consumer) internally without manually checking for all types of events sqs-consumer could possibly raise?

**Comment by robinjmurphy** [comment]
Not currently no. Arguably we shouldn't really be firing the error event when the processMessage function returns an error. Would this change make things clearer for you? You always have access to the processMessage error anyway as it comes from your code.

**Comment by robinjmurphy** [comment]
This would mean that only errors polling/deleting are surfaced by the error event.

**Comment by owais** [comment]
> Not currently no. Arguably we shouldn't really be firing the error event when the processMessage function returns an error. Would this change make things clearer for you? You always have access to the processMessage error anyway as it comes from your code.

This would essentially solve the problem at the cost of a minor inconvenience as I'm using this event to log out own events in different ways. I'd have to write a proxy callback to get errors from handlers, log them and call the real callback.

I guess a good solution would be to have 2 separate events for each type of error.

**Comment by pablovilas** [comment]
I've added a pr for this. https://github.com/bbc/sqs-consumer/pull/19

**Comment by robinjmurphy** [comment]
Fixed in #20. Released as 3.0.0 https://github.com/bbc/sqs-consumer/releases/tag/v3.0.0.
