### ISSUE TITLE
question: is message in-flight if the async handleMessage() function has not returned yet?

### ISSUE THREAD

**Issue by upugo-dev** [bbc/sqs-consumer#165]
Are messages marked as in-flight when sqs-app consumes a message, but the handleMessage function hasn't resolved/returned yet?

**Comment by nspragg** [comment]
A given message will be in-flight when it's been recieved by the handler (but not deleted yet). i.e still processing. The message will be deleted upon successful completion.

**Comment by upugo-dev** [comment]
Thanks for the reply, @nspragg 

So no messages will be pulled from the queue while the handler is processing? 

I’m having a hard time getting the handler function to actually wait for awaits, which gives the effect of processing multiple messages at once
