### ISSUE TITLE
Since version 4.0 to 5.3 sqs-consumer do not remove messages from queue

### ISSUE THREAD

**Issue by grajekk** [bbc/sqs-consumer#169]
### Description
I discovered today, when I updated in my code sqs-library from version 3.8 to 5.2 / 5.3 that after upgrade library do not remove messages from queue after take from queue.

### Expected behaviour
After take message from queue, message should be removed from queue
### Actual behaviour
After take message from queue, message still is in queue (in Messages in Flight)

### Steps to reproduce
1. Put message to queue
2. Take message from queue
3. Check AWS SQS console

### Operating system
Windows

**Comment by nspragg** [comment]
Can you provide a sanitised version of you consumer code?

**Comment by grajekk** [comment]
`export class AwsQueueConsumerImpl extends AwsQueueConnector implements QueueConsumer {

    private client: Consumer;
    private callback: (message: string) => {};
    constructor(queueUrl: string) {
        super();
        const sqsOptions: any = {
            handleMessage: async (message: QueueResponse, done: () => {}) => {
                this.callback(message.Body);
                done();
            },
            queueUrl,
            region: this.AWS_REGION,
            waitTimeSeconds: 10,
        };
        this.client = Consumer.create(sqsOptions);
        this.client.addListener('error', (err: any) => {
            Logger.logException(new QueueReadException(err));
        });
    }

    public subscribe(callback: (message: string) => {}): void {
        this.callback = callback;
        this.client.start();
    }`

**Comment by grajekk** [comment]
And ofc I imported library:
import {Consumer} from 'sqs-consumer'

**Comment by nspragg** [comment]
Why are you using a combination of callbacks and async functions?

**Comment by grajekk** [comment]
you have right. But this combination do not have a impact to this problem. 

In versions after 3.8 of your plugin after take message from queue, in AWS i can see that message is not deleted (is moved to Messages in Flight): 

![2019-05-22 16_22_54-](https://user-images.githubusercontent.com/7073453/58182925-c0a98680-7cae-11e9-9f5b-b08c62639005.png)

And after 10 minutes, message is back to normal queue, and subscribtion is able to take the same message (that served 10 minutes ago).

So please tell me if this is my mistake?
The same code, with version 3.8 works correctly.

**Comment by nspragg** [comment]
Unfortunately, we can't debug your application for you. However, it is advisable to remove the callbacks when upgrading to V5.
