### ISSUE TITLE
Hook before starting processing messages

### ISSUE THREAD

**Issue by lfreneda** [bbc/sqs-consumer#17]
I need to change some settings before processing received messages from sqs.

What do you think about a interception function before starting processing?

It will be provided as options.beforeHandleMessages @ constructor:

``` code
  this.beforeHandleMessages = options.beforeHandleMessages || function(cb) { cb(); }
```

and it would be called as follow @ _handleSqsResponse method:

``` code
  this.beforeHandleMessages(function() { 
    async.each(response.Messages, this._processMessageBound, function () {
      // start polling again once all of the messages have been processed
      consumer._poll();
    });
  })
```

Do you have a better idea?

https://github.com/lfreneda/sqs-consumer/commit/d741ab3fa9cff6ad7da8aabe0a1743a45b9dee31

once you give me ok, I'll unit test it :grinning:

**Comment by lfreneda** [comment]
https://github.com/lfreneda/sqs-consumer/commit/0af884cffbfe399318937d4dd85a5118abd52738

**Comment by robinjmurphy** [comment]
Could you provide a description of what is is you need to do before handling messages? Some example code where you use the consumer would be useful as well.

It may be that you can just call the initial `consumer.start()` inside a callback?

**Comment by lfreneda** [comment]
start is only called once, right? at the beginning.. 

In my implementation I need to periodic train some classification algorithm (eg. https://github.com/NaturalNode/natural) 

I would like to update each batch of received messages, so that is why beforeHandleMessages would be useful.

:cry:

**Comment by robinjmurphy** [comment]
If there's something you need to do before handling a message, you should be able to do it at the top of your `handleMessage` function. I'm not convinced that it's something that the library needs to do for you.

```js
var app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: function (message, done) {
    // do some setup work
    // process message
    done();
  }
});
```

If your 'setup' task is asynchronous, you could use something like `async`:

```js
var async = require('async');

function handleMessage(message, cb) {
  async.series([
    function doSomeSetup(done) {
      // setup
      done();
    },
    function processTheMessage(done) {
      // process
      done();
    }
  ], cb);
}

var app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: handleMessage
});

```

**Comment by lfreneda** [comment]
Ok, no problem <3
