### ISSUE TITLE
Consider adding SQS client https agent keepAlive to documentation

### ISSUE THREAD

**Issue by thales-gaddini** [bbc/sqs-consumer#172]
### Description
I've stumbled on an issue with the AWS SDK where the long polling performance really degraded when there was a high throughput of messages (over 300k in 5min) and a lot of consumers (each consumer was a kubernetes pod). The issue (as describe [here](https://github.com/aws/aws-sdk-js/issues/2371)) is related to the default https agent used by the SQS client with `keepAlive: false`. It isn't an SQS consumer issue directly, but I think it would be nice to have it on the documentation. I can provide a PR if you like the idea.

**Comment by nspragg** [comment]
@thales-gaddini - Happy to accept a PR for this. Cheers.

**Comment by joebowbeer** [comment]
Note: _The easiest way to configure SDK for JavaScript to reuse TCP connections is to set the AWS_NODEJS_CONNECTION_REUSE_ENABLED environment variable to 1. This feature was added in the 2.436.0 release._

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html

**Comment by nspragg** [comment]
@thales-gaddini - many thanks
