### ISSUE TITLE
issue with unstable connection

### ISSUE THREAD

**Issue by tuananh** [bbc/sqs-consumer#174]
[comment]: <> (Please use headings for bugs only, else you can delete) 
### Description

the server i’m using is local and the connection is quite unstable.

what i notice is that sqs-consumer will just stop working in such case and doesn’t continue to receive msg when the connection is connected again.

### Operating system

Debian
node 10 lts

**Comment by nspragg** [comment]
`sqs-consumer` delegates to the aws sdk for network calls. I suggest you look at the aws sdk documentation and pass in your own instance.
