### ISSUE TITLE
Typescript errors in createTimeout return

### ISSUE THREAD

**Issue by pwrnrd** [bbc/sqs-consumer#180]
[comment]: <> (Please use headings for bugs only, else you can delete) 
### Description
Typescript errors in `createTimeout` return. The return is defined by an interface: TimeoutResonse (note PR related to spelling). The return value of `createTimeout` does not meet the `TimeoutResonse` interface.

### Expected behaviour
No Typescript errors

### Actual behaviour
Typescript error for `timeout`:
`Type 'undefined' is not assignable to type 'TimeoutResonse'.ts(2322)`

Typescript error for `pending`:
`Type 'Promise<unknown>' is missing the following properties from type 'TimeoutResonse': timeout, pendingts(2739)`

### Steps to reproduce
1) Copy and paste the following code in your typescript project:
````
  interface TimeoutResonse {
	timeout: NodeJS.Timeout;
	pending: Promise<void>;
  }
  
  function createTimeout(duration: number): TimeoutResonse[] {
	let timeout;
	const pending = new Promise((_, reject) => {
	  timeout = setTimeout((): void => {
		reject(new TimeoutError());
	  }, duration);
	});
	return [timeout, pending]; // <- the errors are here.
  }
  ````
2) Build.

**Comment by nspragg** [comment]
This should be fixed in `5.4.0`
