### ISSUE TITLE
SQS Sent to dead letter queue callback

### ISSUE THREAD

**Issue by afdecastro879** [bbc/sqs-consumer#181]
Will be nice to get a sent to dead letter queue callback. I know can be tricky because is AWS the one that automatically sends the message to the dead letter queue, but at least something that let us know all the retries in the drive policy were done.

Thanks for the nice library

**Comment by nspragg** [comment]
@afdecastro879 - thanks for raising this suggestion. However, we are not looking to support this feature at this time.
