### ISSUE TITLE
Unexpected message handler failure: done is not a function

### ISSUE THREAD

**Issue by geremyCohen** [bbc/sqs-consumer#182]
When running this snippet:

```
const app = Consumer.create({
  queueUrl: SQS_QUEUE_URL,
  region: 'us-east-1',
  batchSize: 10,
  handleMessage: function (message, done) {

    console.log(done);
    console.log(message);// do some work with `message`
    done();
  }
});
```

I can console.log the message, however I get the error:

```
Unexpected message handler failure: done is not a function
```

I am running on Ubuntu 18.04, node 10.16.3.

Any ideas?

**Comment by nspragg** [comment]
@geremyCohen - What version of the `sqs-consumer` are you using? Callback support was dropped from version `4.x.x` onwards.

**Comment by geremyCohen** [comment]
I am using 5.3.0.  I tried using the boilerplate from the home page:

```
const app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: async (message) => {
    // do some work with `message`
  }
});
```
And the messages arrive intermittently (vs my vanilla AWS SDK-based prototype.)

In the docs, it says "Messages are deleted from the queue once the handler function has completed successfully."  but I wasn't clear on what I had to do in the handler to signal a "success" (if anything).

**Comment by rey-narvaez** [comment]
if callback support was dropped in version 4.x.x on

> @geremyCohen - What version of the `sqs-consumer` are you using? Callback support was dropped from version `4.x.x` onwards.

So how do you manage retries in the newer versions i.e done(err)?

**Comment by nspragg** [comment]
Unable to replicate this issue. Closing due to inactively. If you wish to continue this discussion, we can re-open.

**Comment by BravoNatalie** [comment]
> I am using 5.3.0. I tried using the boilerplate from the home page:
> 
> ```
> const app = Consumer.create({
>   queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
>   handleMessage: async (message) => {
>     // do some work with `message`
>   }
> });
> ```
> 
> And the messages arrive intermittently (vs my vanilla AWS SDK-based prototype.)
> 
> In the docs, it says "Messages are deleted from the queue once the handler function has completed successfully." but I wasn't clear on what I had to do in the handler to signal a "success" (if anything).

I'm having the same doubt, how can I signal the success or failure in the handler function?

**Comment by emiliosa** [comment]
@nspragg same issue here `Unexpected message handler failure: timeout of 10000ms exceeded`

version:
```pnpm-lock.yaml
 sqs-consumer:
    specifier: ^11.2.0
    version: 11.2.0(@aws-sdk/client-sqs@3.682.0)`
