### ISSUE TITLE
messageHandler optional callback

### ISSUE THREAD

**Issue by crh3675** [bbc/sqs-consumer#188]
[comment]: <> (Please use headings for bugs only, else you can delete) 
### Description
We recently deployed code and failed to recognize that the `handleMessage` MUST be a Promise (or notated as async).  Our function would always run but did not return a Promise.  This resulted in likely a "super" buildup of messages and eventually put NodeJS 8.9.0 in a state where the CPU would essentially freeze.  It may be good to still have the option of a second callback for those that are old-school like me and overlook the documentation.

```
 messageHandler(message, done) {
    // blah
   done()
 }
```

### Actual behaviour
Bad, unexpected CPU over-consumption, queue overloaded

### Steps to reproduce
Don't send back a Promise or Promise.resolve() in messageHandler function and have a "super" queue that pushes 1,000,000 message per day.

### Operating system
AWS Linux Recent AMI

**Comment by nspragg** [comment]
@crh3675 thanks for raising this issue. 

We decided to remove callback support and it's unlikely we'll revert this decision. Any users still using callbacks and requiring v4+ can convert the `messageHander` easily using `promisify`
