### ISSUE TITLE
isRunning returns true even when not connected to sqs

### ISSUE THREAD

**Issue by scripter-co** [bbc/sqs-consumer#190]
### Description

calling `consumer.isRunning` return true even when configured with an invalid sqs url or invalid credentials.

### Behaviour

Well, this is up for debate I would assume. If the desired behaviour is to return `true` for `isRunning` then I would suggest updating the documentation to be explicit about the behaviour.

### Steps to reproduce

Configure an incorrect queueUrl and you will see that `isRunning` will return true.

**Comment by nspragg** [comment]
@scripter-co - Thanks for raising this issue. 

`isRunning` will return true if the consumer is actively running (polling). See [docs](AWS.SimpleQueueService.NonExistentQueue).  

If the configured queueUrl is invalid, an `AWS.SimpleQueueService.NonExistentQueue` error is thrown. Despite this, the state of consumer is still running, so `isRunning` returning `true`, technically, is correct.

However, it could be debated that continuing to poll when the connection is clearly failing is unnecessary. Still will be addressed in #65
