### ISSUE TITLE
node process close when Ctrl + c

### ISSUE THREAD

**Issue by itzik415** [bbc/sqs-consumer#192]
[comment]: <> (Please use headings for bugs only, else you can delete) 
### Description

I am trying to use: 

```
process.on('SIGINT', function() {
    //some progress....
})
```

for preventing Ctrl + c from closing the node process before the consumer finished his process. What I figured out is that by doing this:

```
process.on('SIGINT', function() {
    var listeners = process.listeners('SIGINT');
    for (var i = 0; i < listeners.length; i++) {
        console.log(listeners[i].toString());
    }
})
```
I can see that I have this method:

`() => {killChrome(); process.exit(130);}`

what causes my node process to close right away when I am doing Ctrl + c

### Expected behaviour

```
process.on('SIGINT', function() {
    //waiting for my work to end and then exit the node process
})
```

**Comment by crh3675** [comment]
Don't you need SIGTERM?

**Comment by nspragg** [comment]
@itzik415 - Thanks for raising this issue. At this time, we will not be implementing behavior to handle ctrl-c interrupt event handling as this can be the responsibility of the calling code, not the library.

**Comment by ypicard** [comment]
This would actually be a lovely feature to have, and beneficiary to many I am sure!
