### ISSUE TITLE
Individual failures are not checked on deleteMessageBatch

### ISSUE THREAD

**Issue by AntonioJuliano** [bbc/sqs-consumer#193]
### Description
In [consumer#deleteMessageBatch](https://github.com/bbc/sqs-consumer/blob/ee31f00af8c2da4637199772fa86fb3d579d01ac/src/consumer.ts#L319) when [batch deleting messages](https://github.com/bbc/sqs-consumer/blob/ee31f00af8c2da4637199772fa86fb3d579d01ac/src/consumer.ts#L331) individual failures are not checked. As per the [AWS docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#deleteMessageBatch-property) "Because the batch request can result in a combination of successful and unsuccessful actions, you should check for batch errors even when the call returns an HTTP status code of 200"

### Expected behaviour
The return value of `this.sqs.deleteMessageBatch` in the callback specifies a list of failed IDs, which should be validated to be empty. If any IDs fail, they should either be retried or the error should be surfaced

### Actual behaviour
Individual failures are silent

### Steps to reproduce
Have AWS return a non-empty `Failed` array

**Comment by AntonioJuliano** [comment]
Also, the same thing with `terminateVisabilityTimeoutBatch`

**Comment by nspragg** [comment]
@AntonioJuliano - thanks for raising this issue.

**Comment by nicholasgriffintn** [comment]
I believe this will be resolved at the same time as this issue:

https://github.com/bbc/sqs-consumer/issues/245

Which is to return a list of successful messages, which when compared would also give you a list of failed messages.

Feel free to reopen if that doesn't resolve this issue.
