### ISSUE TITLE
SQS Consumer <> AWS Lambda

### ISSUE THREAD

**Issue by jgcmarins** [bbc/sqs-consumer#196]
Hello guys. Thanks for this awesome lib.
I have a question related to lambda.
Is there any example or best practices to run a SQS Consumer with AWS Lambda?

**Comment by nspragg** [comment]
@jgcmarins - thanks for your query. 

No, we don't have any examples of running the SQS consumer on AWS Lambda.

**Comment by jgcmarins** [comment]
Great! Any advice or best practices?
Thanks.

**Comment by BrutalSimplicity** [comment]
I don't think that's the way you would handle processing SQS messages on a lambda. **The best practice would be having the lambda triggered when messages are added to the queue.**

https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html

**Comment by crh3675** [comment]
If your throughput is high, Lambda will cost you a mortgage payment so I would not recommend it for high-throughput queues.

**Comment by BrutalSimplicity** [comment]
> If your throughput is high, Lambda will cost you a mortgage payment so I would not recommend it for high-throughput queues.

I think it would depend on the use case and requirements. For many companies this is just the cost of doing business.

**Comment by crh3675** [comment]
Very true, however Lambda also has a concurrency cap per account of 100.  Yes, AWS will adjust this for you but you will need to justify the reasoning with them.  They will throttle your requests and you start building a queue of backlogged Lambda processing.  Every solution has its tradeoffs.

**Comment by BrutalSimplicity** [comment]
1000 concurrent lambda executions, but the number of requests per second is ten times that!

See **Invocation Frequency**
https://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by crh3675** [comment]
I am well aware of the thresholds of Lambda as we have hit them.  I am not replying to continue a discussion, I am replying as a true "use-case" of what is real vs what is not, regardless of documentation.
