### ISSUE TITLE
backward compatibility for older node versions

### ISSUE THREAD

**Issue by neerajyadav** [bbc/sqs-consumer#198]
Is there a way I can use this package with node version 6? Node v6 does not support `async/await`. I can see the project is moved from callbacks to `async/await` in `v4.0.0`. [This](https://github.com/bbc/sqs-consumer/pull/127) and [this](https://github.com/bbc/sqs-consumer/pull/132) pull requests talks about adding support for `async/await` but does not mention much about backward compatibility.

**Comment by nspragg** [comment]
@neerajyadav - thanks for your question. We're are not providing backward compatibility for callbacks.
