### ISSUE TITLE
Consumer service goes down and stops receiving messages when Batch Message Handler method throws error for any message of batch.

### ISSUE THREAD

**Issue by harshpatel30** [bbc/sqs-consumer#199]
[comment]: <> (Please use headings for bugs only, else you can delete) 
### Description: 
Consumer polling for new messages stops polling
### Expected behaviour: 
Send failed message to flight and continue consuming rest of messages
### Actual behaviour: 
Stops polling for new messages
### Steps to reproduce: 
Start polling for batch messages and throw error for first message inside handler
### Operating system
N/A

**Comment by danielgolub** [comment]
@harshpatel30 - it seems like this problem also exists in single "handleMessage" (not just in batch mode)
Do you have a workaround?

**Comment by harshpatel30** [comment]
@danielgolub I have already opened pull request which solved issue for me. https://github.com/bbc/sqs-consumer/pull/200

for handleMessage it throws exception if message handler throws and message goes in flight for me. But not the same for BatchMessageHandler. Just changing error type to processing_error helped me to solve this issue.

Can you please merge this.

**Comment by nspragg** [comment]
@harshpatel30, thanks for raising this issue. I've attempted to replicate this using `sqs-consumer@5.4.0` by throwing an error within the `handleMessageBatch`. The consumer does not stop and continues to processes subsequent messages.

Is this still an issue for you? If so, please provide some sample code to replicate it and I'll investigate.

**Comment by harshpatel30** [comment]
@nspragg Yess its still producible with 5.4.0. Can be fixable with https://github.com/bbc/sqs-consumer/pull/200

**Comment by nspragg** [comment]
The following throws an error within the handler, as you've described and continues polling:

```js
const { Consumer } = require('sqs-consumer');

async function main() {

  const app = Consumer.create({
    queueUrl: 'someQueueUrl',
    handleMessageBatch: async (messages) => {
      throw new Error('batch error')
    }
  });

  app.on('error', (err) => {
    console.error(`error: ${err.message}`);
  });

  app.on('processing_error', (err) => {
    console.error(`processing_error: ${err.message}`);
  });

  app.start();
}

main();
```
