### ISSUE TITLE
Allow message to be deleted off the queue after message reception

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [bbc/sqs-consumer#204]
### Description

We are using this queue for long running (12+ hour jobs). This becomes an issue due to the fact that, until a job is complete, this message is marked as "In Flight". In SQS, messages can only be in flight for a max of one hour before they are either added back to the queue or sent to the dead letter queue. 

It would behoove us to have an option to delete the message of the queue when received, instead of after the message has been processed. Something like

```typescript
export interface ConsumerOptions {
  queueUrl?: string;
  attributeNames?: string[];
  messageAttributeNames?: string[];
  stopped?: boolean;
  batchSize?: number;
  visibilityTimeout?: number;
  waitTimeSeconds?: number;
  authenticationErrorTimeout?: number;
  pollingWaitTimeMs?: number;
  terminateVisibilityTimeout?: boolean;
  sqs?: SQS;
  region?: string;
  handleMessageTimeout?: number;
  handleMessage?(message: SQSMessage): Promise<void>;
  handleMessageBatch?(messages: SQSMessage[]): Promise<void>;
  whenToDeleteMessages: 'before' | 'after';
}
...

 private whenToDeleteMessages: 'before' | 'after';

...

if (this.whenToDeleteMessages === 'before') {
        await this.deleteMessage(message);
}
await this.executeHandler(message);
if (this.whenToDeleteMessages === 'after') {
     await this.deleteMessage(message);
}

...

 if (this.whenToDeleteMessages === 'before') {
        await this.deleteMessageBatch(messages);
      }
      await this.executeBatchHandler(messages);
      if (this.whenToDeleteMessages === 'after') {
        await this.deleteMessageBatch(messages);
      }

```

**Comment by crh3675** [comment]
Why not just call in your handler?

    const instances = Consumer.create({
      handleMessage: async (message) => {
        instance.deleteMessage(message);
        // do stuff here
      }
    })

**Comment by JustAnotherSoftwareDeveloper** [comment]
Honestly I just must have missed the part in the documentation where you can do that. I'm going to try that sometime next week. If it works I'll close out this ticket.

**Comment by nspragg** [comment]
@crh3675 - thanks for your suggestion. 

@JustAnotherSoftwareDeveloper  - `deleteMessage` is not in the documentation because it's a private method as far as Typescript is concerned.  Of course, this is erased in Javascript but please be aware that this method is not officially part of the public api (in this version).

**Comment by JustAnotherSoftwareDeveloper** [comment]
@nspragg That's a decent workaround for now, but it's kinda hacky. Would you consider either exposing this method or implementing my original suggestion in the future?

**Comment by nspragg** [comment]
@JustAnotherSoftwareDeveloper - this issue is related to other issues around deletion, which need to be reviewed. We'll certainly consider this API change in the future. 

However, since you have a workaround, I'll close this ticket for now. 

Thanks @crh3675 @JustAnotherSoftwareDeveloper

**Comment by ayala-orca** [comment]
Is there a plan to expose `deleteMessage`? I also need this capability

**Comment by nicholasgriffintn** [comment]
Sorry, this issue is way to old to really comment here, please raise a new issue or discussion.
