### ISSUE TITLE
how to use it on serverless framework?

### ISSUE THREAD

**Issue by ropi95** [bbc/sqs-consumer#205]
[comment]: <> (Please use headings for bugs only, else you can delete) 
### Description
Hi anyone have use this plugin at AWS Lambda? i have trying use it on AWS Lambda but still not working, because i just learn new this stack technologies... can you give me how to use it on AWS Lambda.. thank you

### Expected behaviour
running and listen sqs
### Actual behaviour
not running
### Steps to reproduce
using serverless to AWS
### Operating system
ubuntu 18.04

**Comment by erwineverts** [comment]
AWS has thier own implementation to receive sqs messages.
If you are using the serverless framework, check: https://serverless.com/framework/docs/providers/aws/events/sqs/
