### ISSUE TITLE
Question handling SQS authentication using EC2 assumed role

### ISSUE THREAD

**Issue by gfrileux** [bbc/sqs-consumer#206]
Hi,
This is more of a question than a problem.
We have a Node applicaiton running inside an EC2 instance, The EC2 instance has a bunch of rights granted, to access things like S3, DynamoDB ad SQS.
When using the AWS SDK to access S3 (so doing something like `const s3 = new AWS.S3();` and then `s3.getObject({blabla})`), the EC2 instance automatically recognises that we're using the AWS SDK without having specified any credentials, and so it uses its own role to access S3. So far so good.

The issue arises with SQS though. We have a setup that looks like this:
```
import AWS from 'aws-sdk';
import Consumer from 'sqs-consumer';
import { AWS_REGION } from '../config';

// we are not passing any AWS Key as the EC2 machines have the right role to read/write from the SQS queue
AWS.config.update({
  region: AWS_REGION,
});

 const sqs = new AWS.SQS();

export default (queueUrl, messageHandler) =>
  Consumer.create({
    batchSize: 1,
    visibilityTimeout: 0,
    queueUrl,
    handleMessage: messageHandler,
    sqs,
  });
```
I would have thought that this would work in the sae way our S3 access works (i.e. using the EC2 role 'magic') however it doesn't for SQS. When I try to log the consumer after creation, I see this:
```
    "message": {
        "queueUrl": "https://.......", <- removed this but it's correct
        "attributeNames": [],
        "messageAttributeNames": [],
        "stopped": true,
        "batchSize": 1,
        "visibilityTimeout": 0,
        "terminateVisibilityTimeout": false,
        "waitTimeSeconds": 20,
        "authenticationErrorTimeout": 10000,
        "sqs": {
            "config": {
                "credentials": null,
                "credentialProvider": {
                    "providers": [
                        null,
                        null,
                        null,
                        null
                    ]
                },
                "region": "eu-west-1",
                "logger": null,
                "apiVersions": {},
                "apiVersion": null,
                 ...... <- a whole bunch of other attributes
}
```
The part saying `credentials: null` is obviously concerning.

Do you have any ideas/suggestions to work around this ?
We could create AWS keys for the EC2 and use those explicitly but that defeats the purpose of using the EC2 assumed role capability.

Thanks !!

**Comment by fempyrean** [comment]
Hey @gfrileux, sorry to bring back this issue, but I'm going through the exact same issue. Did you find a solution for this?

**Comment by himalreddy** [comment]
I am also facing same issue. any solution for this?
