### ISSUE TITLE
didn't receive the message

### ISSUE THREAD

**Issue by skiod** [bbc/sqs-consumer#213]
I sent two messages but i received only one, then it shows "message empty"

logs from my app
first meessage : 
queueUrl : https://sqs.us-east-2.amazonaws.com/xxxxxxx/tasks 
messageId : aa1fdc71-a19c-4263-9bf0-xxxxxx <--------------- ##1
 
second message : 
queueUrl : https://sqs.us-east-2.amazonaws.com/xxxxxxx/tasks
messageId : ca855b33-be5a-4f47-806f-xxxxxx

consumer

message received {
MessageId: 'aa1fdc71-a19c-4263-9bf0-xxxxxxx', <--------------- ##1 
ReceiptHandle: 'xxxxxxxxxxxxxx',
MD5OfBody: 'xxxxxxxxxxxxx',
Body: '{"test":1}'
}

message processed
message empty

i don't know why message2 didn't consume ??

```
var AWS            = require('aws-sdk');
const { Consumer } = require('sqs-consumer');
const task         = require('../../jobs/task');

AWS.config.update({
  accessKeyId: process.env.SQS_API_KEY,
  secretAccessKey: process.env.SQS_API_SECRET_KEY,
  region: process.env.SQS_REGION
});

  const app = Consumer.create({
    queueUrl: `https://sqs.${process.env.SQS_REGION}.amazonaws.com/${process.env.SQS_ACCOUNT_ID}/tasks`,
    waitTimeSeconds: 20,
    visibilityTimeout: 90,
    handleMessage: async (message) => {
          let obj = JSON.parse(message.Body)
          //my logic here
          await task.startFetching(obj.test)
          return;
    }
  });
  
  app.on('error', (err) => {
    console.log('[SQS WORKER]',err.message)
  });
   
  app.on('processing_error', (err) => {
    console.log('[SQS WORKER]',err.message)
  });
  
  app.on('timeout_error', (err) => {
    console.error('[SQS WORKER]',err.message);
  });
  
  app.on('message_received',(message) => {
    console.log('[SQS WORKER]','message received',message);
  })
  
  app.on('response_processed',()=> {
    console.log('[SQS WORKER]','message processed')
  })
  
  app.on('stopped',()=> {
    console.log('[SQS WORKER]','message stopped')
  })

  app.on('empty',() => {
    console.log('[SQS WORKER]','message empty')
  })

  app.start();
  console.log(`[TASK WORKER] is listening...`);

```

and please another thing how can i let the consumer consume one message and wait my logic until it done then receive the next one

thank you in avance

**Comment by crh3675** [comment]
The message handler should return a Promise which is one thing that may be an issue:

`    handleMessage: async (message) => {
          let obj = JSON.parse(message.Body)
          //my logic here
          return task.startFetching(obj.test)
        }`

The other part of the question probably would need additional configuration:

`  const app = Consumer.create({
    queueUrl: `https://sqs.${process.env.SQS_REGION}.amazonaws.com/${process.env.SQS_ACCOUNT_ID}/tasks`,
    waitTimeSeconds: 20,
    visibilityTimeout: 90,
     batchSize: 1,
    handleMessage: async (message) => {
          let obj = JSON.parse(message.Body)
          //my logic here
          await task.startFetching(obj.test)
          return;
    }
  });`

And if you want to pause the consumer between calls, you can use:

`app.stop();` and then `app.start()` to restart the polling.

**Comment by nspragg** [comment]
@crh3675 - thanks. 

Happy to reopen if this in still and issue.
