### ISSUE TITLE
change batch visibility to zero based on failed messages

### ISSUE THREAD

**Issue by HuskyDanny** [bbc/sqs-consumer#214]
**The problem**
We have a case where we want to execute batch of messages (to utilized the async nature of nodejs), and if error occurs, just return the failed messageId and change the visibility of these failed message to zero for retrying.
**Suggested solution**
Add another field like batchMessageHandlerRetrying, so we could perform the normal batch message handling and change the visibility to zero only for those failed (not all messages)
**Alternatives considered**

**Additional context**

**Comment by crh3675** [comment]
**handleMessage** allows you to handle each message individually.  If you are using **handleMessageBatch** and expect to "handle each individually", I would say you are using the wrong method.  Batch size is 1 by default.  If a message fails, simply **return Promise.reject()**.

    const myFunction = async message => {
        // run some process
        if (success) {
            return Promise.resolve();
        } else {
            return Promise.reject('Process failed, return to batch');
        }
     }

    handleMessage: async (message) => {
        return await myFunction(message);
    }

Either method is Asynchronous so I am not sure I understand the comment (to utilized the async nature of nodejs)?

**Comment by HuskyDanny** [comment]
Thanks for replying.
So right now my consumer handle message sequentially, one message at a time, because if some message fails, I want to redrive these failed. But that's very slow to process messages, since most of them are just doing http request. And from the source code, I see the consumer only poll the next message if the previous one succeeds or fails.
I noticed there is handleMessageBatch, so I could asynchrously process messages from the batch, but for that if one of message from the batch fails, the consumer will retry all messages from the batch, is it possible just to process these fails?

**Comment by nspragg** [comment]
Closing due to inactively. Happy to reopen if further discussion is required.
