### ISSUE TITLE
Automatically extend message visibility timeout

### ISSUE THREAD

**Issue by bencampion** [bbc/sqs-consumer#218]
**The problem**
At the moment there is no easy way to extend the visibility timeout for a message. If you want to use sqs-consumer for consuming long running tasks then you have to set `visibilityTimeout` to a large value and enable `terminateVisibilityTimeout`. This is not ideal as the visibility will only be reset when `processing_error` occurs and it will always set it back to `0`, which means there will be no delay before reprocessing the message again.

**Suggested solution**
Add a new number option called `heartbeatInteval`. Setting this option would enable the following behaviour:
- Call `setInteval` before executing the message handler to schedule an interval to run every `heartbeatInteval` seconds.
- When the interval fires, it sets the visibility timeout to the number of elapsed seconds since the interval was scheduled and adds `visibilityTimeout` to it. 
Example with `visibilityTimeout=40` and `heartbeatInteval=30`:
  - message is retrieved from queue with visibility timeout set to 40 seconds
  - after 30 seconds the visibility timeout is set to 70 seconds
  - after 60 seconds the visibility timeout is set to 100 seconds
- The interval is cleared in a `finally` block once the message has been successfully processed.

For batch processing, the visibility would extended for every message in the batch using the batch update method. There should probably be some config validation to make sure that `heartbeatInteval` is less than `visibilityTimeout`.

**Alternatives considered**
I initially considered having a separate value for how much to extend the visibility by, but I think that in most cases extending it by `visibilityTimeout` would be sufficient.

**Additional context**
- My team is willing to do all the work required to implement this functionality as it's something we'd like to use ASAP.
- If we do the work then we'll probably want to update existing tests to use [fake timers](https://sinonjs.org/releases/latest/fake-timers/) as it would be hard to test this feature sensibly will real timers.
- This is feature request is similar to https://github.com/bbc/sqs-consumer/issues/171.

**Comment by jeanrauwers** [comment]
Hey, @bencampion we are discussing this issue and we would like to know a few extra details.
How long do your jobs can run for?

> "This is not ideal as the visibility will only be reset when processing_error occurs and it will always set it back to 0, which means there will be no delay before reprocessing the message again"

What's the side effects of no delay for you?

**Comment by bencampion** [comment]
We're processing potentially very large files and the length of the job is proportional to the size of the file. I'm not sure what the longest job would take, but we'd probably need to allow at least an hour, even though we know many jobs will complete in a few minutes. We're trying to avoid introducing limits on the size of the file we can process and the timeout will end up becoming a limit.

The issue with no delay means there is no back-off before retrying. If a job fails because of a transient error then we don't want to retry it immediately, but we also don't want to wait hours before trying either.

**Comment by crh3675** [comment]
I don't like this resolution in this project.  A consumer should acknowledge the message and handle failures or long-running processes within the application, not transfer the responsibility back to SQS.  SQS is a queuing service, not a task manager.

**Comment by crh3675** [comment]
@bencampion We process very large files as well (1.2GB Landsat data) and use separate SNS notifications for different "states" of completeness.  I can perhaps help you on this a little but changing the timeout is not the correct way to work with AWS SQS.

**Comment by jeanrauwers** [comment]
@bencampion  hey Ben, I am interested in seeing your view on this one, thank you!

**Comment by bencampion** [comment]
I'm not aware of anything in the SQS documentation that says using SQS in this way is wrong. The best practices page explicitly suggests creating heartbeat if you don't know how long it will take to process a message: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/working-with-messages.html#processing-messages-timely-manner

Extending the visibility timeout like this won't always be appropriate, but it's good fit for some of the things we want to do. I don't want to create my own task management architecture when all of the features I require are already built into SQS.

**Comment by crh3675** [comment]
In my experience, I have found that although the documentation might say that is a reasonable approach, this library is not the way to tackle that endeavor.  In your case, it is "not appropriate" if you are in fact processing large files.  I recommend submitting process-state SNS messages to the SQS queue.  I do understand your challenge but this project is not meant to be a task manager for long-running tasks and I feel strongly against this feature request.
