### ISSUE TITLE
Add failure reason to Message Attributes

### ISSUE THREAD

**Issue by nhnicwaller** [bbc/sqs-consumer#221]
Feature Request: add custom data to Message Attributes after processing failure

We are using sqs-consumer and it works great. But sometimes our application fails to process a message for whatever reason, even after a few retries, and our SQS redrive policy sends the failed message to a dead letter queue. Our usual troubleshooting approach is to look through our logs to find correlated events indicating why the message ended up there. But it would be *much* nicer if there was a way for us to augment the Message Attributes with an explanation of how processing failed (the last time). This would also allow us to make our automated alerts more detailed.

I'm not sure exactly how this might work in sqs-consumer. Maybe the text of the throw exception gets added as an attribute? Or maybe check for presence of a `message_attributes` key on the exception and use that to add data? The exact usage isn't super important -- I'm just looking for some way to add useful metadata to failed tasks.

**Comment by crh3675** [comment]
There is a way to possibly use a Promise.allSettled wrapper in your `handleMessageBatch` and re-submitting failures back to the queue using the `consumer`.

```javascript
const consumer = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessageBatch: batch => {
    const deferred = [];
    for (let count = 0; count < batch.length; count++) {
      const message = batch[count];
      deferred.push(new Promise(resolve, reject) {
        // something to do with message
      }); 
    }
    Promise.allSettled(deferred).then(results => {
      results.forEach(settled => {
        if (settled.status === 'rejected') {
          message.MessageBody = Message.Body;
          message.MessageAttributes = [
            {
               DataType: 'String',
               StringValue: settled.reason
            }
          ];
          consumer.sqs.sendMessage(message);
        }
      });
      return Promise.resolve();
    });
  }
});
```

**Comment by nhnicwaller** [comment]
@crh3675 Thanks for that suggestion, that seems perfectly reasonable. Because it seems that this behaviour can be implemented without support of the sqs-consumer library, I'm going to close this issue.
