### ISSUE TITLE
waitTimeSeconds cannot be 0

### ISSUE THREAD

**Issue by TyLindberg** [bbc/sqs-consumer#223]
**Describe the bug**
Right now if `waitTimeSeconds` is set to 0 it will get changed to the default of 20.

**To Reproduce**
Steps to reproduce the behaviour:
1. Initialize a Consumer with `waitTimeSeconds` set to 0
2. Monitor the frequency `handleMessage` gets called

**Expected behaviour**
I would expect this to result in the consumer using short polling rather than the default behavior of long polling at 20 second intervals.

**Additional context**
Seems like the issue stems from this bit of code: https://github.com/bbc/sqs-consumer/blob/d11d19cc8ef8333a19f0badca31ea77e7f3890bc/src/consumer.ts#L130

**Comment by nspragg** [comment]
@TyLindberg - thanks for raising this. We're accepting PRs for this.
