### ISSUE TITLE
Running multiple queues in one Node.JS thread causes queue to suddenly stop fetching messages

### ISSUE THREAD

**Issue by kevinlu1211** [bbc/sqs-consumer#224]
**Describe the bug**
When running multiple queues on my Node.JS server one of the queues will suddenly stop receiving messages, but when I restart the server everything works.

**To Reproduce**

I am initializing my server like so:

```
await WrappedConsumer.initialize(queueUrl: ...)
await WrappedConsumer.initialize(queueUrl: ...)
await WrappedConsumer.initialize(queueUrl: ...)
...
app.run()
```
The pseudocode for WrappedConsumer is like so:
```
const initialize = async (queueUrl, eventActionMap = defaultEventActionMap) => {
  internals.consumer = Consumer.create({...});
  await internals.consumer.start();
  attachEventHandlers(internals.consumer, logger);
};
```
I have three queues that run all fetch messages at the same time. The problem that I am facing is that sometimes one of the queues will suddenly stop pulling messages even though there are still messages in the queue.

**Expected behaviour**
The queues continuously polls for new messages

**Additional context**
Reading the [SQS FAQ](https://aws.amazon.com/sqs/faqs/) there is an extract:

> For example, if your application uses a single thread to poll multiple queues, switching from short polling to long polling will probably not work, because the single thread will wait for the long-poll timeout on any empty queues, delaying the processing of any queues that might contain messages.

I was wondering if this is of any relevance. If it is then shouldn't the empty queues block the other queues from receiving messages when the server is started up, and not 10 minutes into the server running? 

**EDIT**
Also, if I have initialized my queue with `ReceiveMessageWaitTime=0` does using `bbc-consumer` still do long polling?

I have read through the source code and since `WaitTimeSeconds` is set to 20 seconds by default which is used in the [receive message call](https://github.com/bbc/sqs-consumer/blob/035bc7dd084ff4fc824e69d75aa11495bc19e5fd/index.js#L77) and since short polling [is defined as](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-short-and-long-polling.html):

> Short polling occurs when the WaitTimeSeconds parameter of a ReceiveMessage request is set to 0 in one of two ways:
> 
> 1. The ReceiveMessage call sets WaitTimeSeconds to 0.
> 2. The ReceiveMessage call doesn’t set WaitTimeSeconds, but the queue attribute ReceiveMessageWaitTimeSeconds is set to 0.

Hence we can conclude that even if the queue is initialized with `ReceiveMessageWaitTime=0` by using the default settings during initialization of `bbc-consumer` it will do long polling

**Comment by crh3675** [comment]
I think the issue is trying to `await` in consecutive order which is creating a blocking effect for future queues you are polling.  It sounds like you probably should be running each consumer in it's own thread.  You can do this with a `child.spawn` or even try a process manager like `pm2` to iterate which queue to use based on the `process.env.pm_id`.  What you want is to have 3 separate consumers that are self-managed that have no reliance on the other.

**Comment by kevinlu1211** [comment]
I have wrapped `bbc-consumer` such that during initialization I initialize the consumer, then call `await consumer.start()`
