### ISSUE TITLE
adding concurrency 

### ISSUE THREAD

**Issue by tomer-yechiel** [bbc/sqs-consumer#229]
**The problem**
I want to process messages in parallel X at a time, but now I can only process messages in parallel in batches
**Suggested solution**
add some kind of promise pool, whenever a new message is done, take the next message from the queue so always X messages are being processed at the same time

**Alternatives considered**
none

**Additional context**
none

are you open to PRs?

**Comment by jeanrauwers** [comment]
Hi, @tomer-yechiel.

Thanks for the suggestion but we will not be supporting concurrency at this time.

You can start multiple instances of the consumer if you need so.

Regards

Jean

**Comment by tomer-yechiel** [comment]
@jeanrauwers I know i can spawn multiple instances but its exactly what i need.
