### ISSUE TITLE
consumer does not regulate itself and takes 100% cpu when no AWS creds given

### ISSUE THREAD

**Issue by Morriz** [bbc/sqs-consumer#23]
I just spent some time finding out the hard way (after restarting a virtual machine in the cloud) that your library does not inspect it's environment, nor does it regulate its own sanity...pffff

please kill the loop if the environment is not sane, as in no aws creds found etc...

**Comment by robinjmurphy** [comment]
Thanks for the feedback. This is an issue we'd like to fix. Will try and get something out, or a PR would be very welcome.

**Comment by Morriz** [comment]
Of course. I have some logic like that lying around somewhere. Will do when I have my power adapter back from work :p
