### ISSUE TITLE
callback error

### ISSUE THREAD

**Issue by SivaVijayakumar** [bbc/sqs-consumer#230]
const app = Consumer.create({
queueUrl: queueUrl,
attributeNames: [‘All’],
messageAttributeNames: [‘All’],
handleMessage: function (message, doneCallback) {
// console.log(‘ — — — — — — — — ‘, arguments)
console.log(‘ Response Data => ‘, JSON.stringify(message, null, 2))
callAPI(urlResultObj, (error, jobs) => {
if (error) {
console.log(‘ ==== ERROR=====> ‘, error)
return doneCallback(error)
}
console.log(‘ ==== jobs=====> ‘, jobs)
return doneCallback(null, jobs)
});
},
sqs: new aws.SQS({
httpOptions: {
agent: new https.Agent({
keepAlive: true
})
}
})
});
Hi, I have written the above code by taking reference as your code. I am getting the below error.
TypeError: doneCallback is not a function
Please, someone, help me with this issue?

**Comment by nspragg** [comment]
@SivaVijayakumar - We no longer support callbacks. If you're using Version 4+ you need to use `async` functions for message handlers.
