### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by vladcazacu** [bbc/sqs-consumer#237]
**Question**
The `heartbeatInterval` option is documented in `master`, but it's not part of any release yet (latest release is 5.4.0 from Sep 2019). Any news on when 5.5.0 will be out so we can use this feature and continue using the package through npm?

**Comment by teyou** [comment]
is there no one maintaining this repo anymore?

**Comment by nspragg** [comment]
@vladcazacu - 5.5.0 released.
