### ISSUE TITLE
SQS stopped polling.

### ISSUE THREAD

**Issue by mashoodrafi6** [bbc/sqs-consumer#241]
**Describe the bug**
The polling of SQS messages for various queues is working fine but the **SQS stopped** polling twice and all of the SQS messages started to add up in queue. **I restarted the server and the queues started to be polled and process instantly**. After a month same thing happened and SQS stopped polling and messages started to add up in queues, restarted the server and SQS began to poll and process queues. I've been using several SQS for a long time but this has happened twice in a span of 2 months on production server.
Also no error was triggered on events using '**error**' and '**processing_error**'. 

Version of sqs-consumer is **"^5.4.0"**. 
Version of aws-sdk": "^2.585.0

I've seen a similar issue being reported previously but that was closed with a fix. 
https://github.com/bbc/sqs-consumer/issues/130
Any idea what could possibly be the reason ?

**To Reproduce**

**Expected behaviour**
Do not expect SQS to stop polling. Also why did the server restart solved the issue and SQS started to poll again which was in a halt state.

**screenshots**
![image](https://user-images.githubusercontent.com/56217788/91961938-4f67d880-ed25-11ea-8ccb-4a9d4fa87df4.png)

**Additional context**
I'm using node.js (v10.19.0) deployed on docker.

**Comment by KencyK** [comment]
sqs version : "5.4.0",

**Comment by KencyK** [comment]
sqs : 5.4.0
aws-sdk : 2.611.0

**Comment by larsjarek** [comment]
Same issue here. 

sqs : 5.4.0
aws-sdk : 2.688.0
node version : 12

**Comment by Tobska** [comment]
Also encountering this issue, from time to time.

"sqs-consumer": "^5.4.0",
"aws-sdk": "^2.658.0",
node version: 12

Also posting a picture from Sentry that caught this error.
![Screen Shot 2020-09-22 at 11 16 14 AM](https://user-images.githubusercontent.com/17682109/93841312-c3165900-fcc5-11ea-8862-d9dddab49741.png)

**Comment by mfrobben** [comment]
We just hit this this morning, sqs-consumer 5.4.0, node 10, aws-sdk 2.708.0. No errors emitted.

**Comment by benjamin-greve-cove** [comment]
We also encountered this today:
- sqs-consumer 5.4.0
- Node 14.7.0 (using the node:14.7.0-buster Docker image)
- aws-sdk 2.743.0

No errors were emitted.

**Comment by artur-ma** [comment]
same issue 

"sqs-consumer": "^5.4.0"
"aws-sdk": "^2.574.0",

**Comment by achallett** [comment]
Can you post your consumer options? There may be a common configuration setting when this issue is occurring (such as keeping the http connection open, or not providing a handler timeout).

**Comment by artur-ma** [comment]
@achallett 
1. batchSize: 10, 
2. custom sqs client with https keepAlive client is used (https://www.npmjs.com/package/agentkeepalive)
3. visibilityTimeout: 60

+ multiple instances(10) of sqs-consumer running in the same nodejs process

**Comment by KencyK** [comment]
> Can you post your consumer options? There may be a common configuration setting when this issue is occurring (such as keeping the http connection open, or not providing a handler timeout).

@achallett here you go 

`
import AWS from 'aws-sdk';
import { Consumer } from 'sqs-consumer';
import { awsConfig } from '../../common/config/config';
import { Logger } from '../../common/config/logger';

const logger = Logger.getInstance(module);

const sqs = () => {
  AWS.config.update({
    region: awsConfig.region,
  });
  return new AWS.SQS();
};

/**
 * Consumer listening to messages from AWS SQS.
 *
 */
const sqsAudit = Consumer.create({
  queueUrl: awsConfig.sqsAuditUrl,
  sqs: sqs(),
  handleMessage, // defined in a different file
  messageAttributeNames: ['event'],
});

sqsAudit.on('error', (err: Error) => {
  logger.error(`Error while interacting with queue: ${err}`);
});

sqsAudit.on('processing_error', (err: Error) => {
  logger.error(`Error while processing message: ${err.message}`);
});

sqsAudit.on('timeout_error', (err: Error) => {
  logger.error(`Handle message timed out: ${err}`);
});

export default sqsAuditLogApp;
`

**Comment by Adil93** [comment]
Could you please share an update on this issue  @achallett ?

**Comment by AG-Teammate** [comment]
Could be an upstream issue? There are similar reports in the AWS repo with no clear resolution, e.g. https://github.com/aws/aws-sdk-js/issues/3142#issuecomment-622618335

If so, should we implement our own backup timeout for receiveMessage?

**Comment by ariesmcrae** [comment]
Here's a possible workaround. Do you foresee any problems with this approach?

// Check every 30 seconds to see if poller is still running, then re-start it

```javascript
setInterval(() => {
  const isRunning = app.isRunning

  logger.info(`sqs poller isRunning? : ${isRunning}`)

  if (!isRunning) {
    logger.warn('sqs poller is not running. Re-starting now.')
    app.start()
  }
}, 30000)
```

**Comment by pawelszczerbicki** [comment]
Fixing problems by continuous restart its not a good approach :) In my opinion its a way better to find and solve source of problem :)

**Comment by swapnil0545** [comment]
Hi,

I am facing same scenario in my product which is going to go live in a week.
Is there any good work around for this. Don't have the time to remove this now. 
@AG-Teammate @pawelszczerbicki @ariesmcrae @KencyK @Tobska @mfrobben

**Comment by swapnil0545** [comment]
Does this help? How to try this or has anyone tried this? https://stackoverflow.com/questions/37111431/amazon-sqs-with-aws-sdk-receivemessage-stall

**Comment by ashprojects** [comment]
Facing this issue as well. It's freezing in my production environment.

**Comment by mashoodrafi006** [comment]
I removed **await** key word from the function called inside SQS consumer and handle retries myself and since then it haven't occurred.

**Comment by titobundy** [comment]
I've a same issue, I use NestJS with the @ssut/nestjs-sqs library that depends on sqs-consumer, after a few days, the consumer is not able to receive any more messages from aws (the microservice containing the consumer is still working properly), but when the kubernetes pod is restarted,  the consumer in my app starts polling and processing messages from queues again.

```
node version: 12.19

"@nestjs/core": "^7.6.15",
"aws-sdk": "^2.806.0",
"@ssut/nestjs-sqs": "^1.0.0",
    -> ssut/nestjs-sqs dependencies
         "aws-sdk": "^2.728.0",
         "sqs-consumer": "^5.4.0",
         "sqs-producer": "^2.0.2",
```

Register SqsModule in app.module.ts

```
SqsModule.registerAsync({
  imports: [AppConfigModule],
  useFactory: async (configService: ConfigService) => {
    const sqs = new AWS.SQS({          
      accessKeyId: configService.get(Configuration.AWS_ACCESS_KEY_ID), 
      secretAccessKey: configService.get(Configuration.AWS_SECRET_ACCESS_KEY),
      region: configService.get(Configuration.AWS_REGION),
    });
    
    return {
      consumers: [
        {
          name: `${configService.get(Configuration.QUEUE_NAME)}`,
          queueUrl: `${configService.get(Configuration.QUEUE_URL)}`,
          sqs
        },           
      ],
      producers: [],
    };
  },
  inject: [AppConfigService],
}),
```
Consumer Service

```
@Injectable()
export class SQSMessageHandler {

  @SqsMessageHandler(`${process.env.QUEUE_NAME}`)
    public async handleMessage(message: AWS.SQS.Message) {
      this.logger.debug(`Incomming message: ${message.MessageId} `, CostosMessageHandler.name);

      ...
  }
}
```

**Comment by anoop-chauhan** [comment]
> I removed **await** key word from the function called inside SQS consumer and handle retries myself and since then it haven't occurred.

Hi @mashoodrafi006 , can you please elaborate how you handled retries on any error

**Comment by mashoodrafi006** [comment]
I wrote a cron command that would bulk update the data between micro-services after hourly interval to patch for the events that were not consumed. @anoop-chauhan

**Comment by karthikpawar** [comment]
I was facing this issue because the "handleMessage" of the consumer instance is not resolved for a specific poll, and this caused the the consumer to stall.
Fix: Resolved "handleMessage" method for all possible cases, and added better error handling.

**Comment by devdabiri** [comment]
> I was facing this issue because the "handleMessage" of the consumer instance is not resolved for a specific poll, and this caused the the consumer to stall. Fix: Resolved "handleMessage" method for all possible cases, and added better error handling.

Pls can you elaborate more on this. Having same issue for long now

**Comment by devShHong** [comment]
so what is possible workaround?

**Comment by srprinz** [comment]
Has anyone found a solution for this? I am still facing this issue.

**Comment by msuganthan** [comment]
I am facing this issue, any solution?

**Comment by judiel-camonapp** [comment]
i'm facing the same issue here, any solution?

**Comment by hayes-crowley** [comment]
Facing the same issue as well.

@[karthikpawar](https://github.com/karthikpawar) could you elaborate a bit on the changes you made to `handleMessage` / what case was causing it to not resolve? 

Was it an unresolved Promise? Were you not returning within a function somewhere?

**Comment by topmonroe9** [comment]
> I've a same issue, I use NestJS with the @ssut/nestjs-sqs library that depends on sqs-consumer, after a few days, the consumer is not able to receive any more messages from aws (the microservice containing the consumer is still working properly), but when the kubernetes pod is restarted, the consumer in my app starts polling and processing messages from queues again.
> 


Hi. Is this still an issue? Looking in to nest module working through SQS and still not sure if I should use this package and nest-sqs or should I write some boilerplate with aws-sdk? Thanks for any advise on this in advance

**Comment by prakash-velotio** [comment]
Facing same issue.
I am using `@ssut/nestjs-sqs` library which uses internally this one.

Is there any update on this one ?

**Comment by vhd-luke** [comment]
Same issue here when using `@ssut/nestjs-sqs`

**Comment by Banner2404** [comment]
We had the same issue where consumer was stopping polling for messages randomly. However after investigation we detected an issue with a very slow database request inside the handler that was blocking the consumer.
The consumer has been working flawlessly since we resolved the database issue.

**Comment by kaansan** [comment]
We have faced same problem twice. Can you eloborate this case with an example?. We have restarted the application (K8 pods) and it resolves the problem. Consumers started the poll messages.

**Comment by emdneto** [comment]
We are facing the same issue using sqs-consumer v5.6.0 and node v14.19.1/v16.16.0, We are running the applications (k8s pods) on an EKS cluster. Has anyone found a solution for this? or maybe there's something we can investigate?

**Comment by kevlened** [comment]
Due to default behavior in Node, setting a request timeout seems to work for some users:

https://github.com/aws/aws-sdk-js/issues/367#issuecomment-56875656

**Comment by sebastiaorealino** [comment]
Same issue here :/

**Comment by iamseki** [comment]
I was facing the same issue using sqs-consumer v5.4.0. My environment was having temporary dns problems and sometimes sqs host becames inaccessible which causes `Unhandled promise rejection` exceptions and then the listener sudenly stopped polling. Upgrade sqs-consumer to [v5.7.0](https://github.com/bbc/sqs-consumer/releases/tag/v5.7.0) fix this behavior in my case. Hope this can be useful for someone.

**Comment by levanluu** [comment]
Same issue here 👍

**Comment by mistadikay** [comment]
Same issue here, version 5.7.0

**Comment by Sanguinettecode** [comment]
Pessoal, verifiquem se handleMessage está gerando algum erro. Isso por causar a interrupção do pulling das mensagens.

` 
@SqsMessageHandler(MessageConfig.SQS_QUEUE_NAME, false)
    async handleMessage(message: AWS.SQS.Message) {
        const data: any = JSON.parse(message.Body)
        
        // Algum erro não aparente aqui //

        console.log(data)
    }
  

   @SqsConsumerEventHandler(MessageConfig.SQS_QUEUE_NAME , 'processing_error')
    public onProcessingError(error: Error, message: AWS.SQS.Message) {
        console.log(error, message)
 
      //adicionem esse carinha aqui pra verificar algum erro no handleMessage
    }

`
Espero que ajude

**Comment by mikejackowski** [comment]
The same issue, unfortunately. I assume this library is not maintained anymore, any alternatives/guides on how to do it in nodejs?

**Comment by nicholasgriffintn** [comment]
There's nothing really specific here for us to work from looking through all of the comments, that said, may of the examples sound like issues with down stream dependencies or particular set ups.

If you still think this is an issue, then this might be better as a discussion until a firm reason has been found and that reason is this library.

**Comment by Fsociety-sem** [comment]
Check the delay parameter in queue settings
![image](https://user-images.githubusercontent.com/73710339/207979002-566e0aa5-1f2b-484f-9ac9-bf7a435d2d6c.png)
