### ISSUE TITLE
handleMessageBatch - individually acknowledging/deleting upon success

### ISSUE THREAD

**Issue by walshe** [bbc/sqs-consumer#245]
**Question**
If I set batchSize to 10, so that I can receive more than one message, how can I individually checkpoint each message so that if message #9 fails I don't end up having to reprocess the forst 8 again ?

**screenshots**

**Additional context**
I want to add more throughput to my consumer by using handleMessageBatch. However I want to be able to acknowledge successful processing of messages individually in case there is a failure processing one of the messages in the batch

**Comment by guizoxxv** [comment]
I had the same doubt. Looking at the [code](https://github.com/bbc/sqs-consumer/blob/3cafbb7e2b4847e3afbd6ebb3cc17bbc6faceb09/src/consumer.ts#L333) this is not possible but it would be a nice feature.

Meanwhile my solution was to manually delete the processed messages inside `handleMessageBatch` it one fails.

Here is a [gist](https://gist.github.com/guizoxxv/078444ec1b65801c74aa61d5c339b562) with an example.

**Comment by efiShtain** [comment]
@guizoxxv I've added a pull request to support partial batch ack by returning an array of successful messages from handleMessageBatch

you can try and see if it works for you

https://github.com/bbc/sqs-consumer/pull/255

**Comment by nicholasgriffintn** [comment]
https://github.com/bbc/sqs-consumer/pull/255 has been merged and will be released when the library is next published, which may be after Christmas.
