### ISSUE TITLE
Plans to support aws-sdk v3?

### ISSUE THREAD

**Issue by ericyd** [bbc/sqs-consumer#251]
**Question**
AWS SDK v3 was released in December 2020: https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.0.0.

Does this library plan to eventually support it?

I figured an issue might be a useful way to track this effort if it's planned.

The [v3 API is pretty different](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sqs/index.html), but the major benefit I could see here is that it's modular by design

**Comment by jontroncoso** [comment]
Not trying to blindly bump this, but it looks like there's a PR that just needs some minor merge-conflicts. I'm sure there are many people in my situation hoping to use this, but can't due to the old version being used.

**Comment by thales-maciel** [comment]
well...

**Comment by nicholasgriffintn** [comment]
Watch this space, looking into this one now.

**Comment by nicholasgriffintn** [comment]
This issue should probably be resolved at the same time:

https://github.com/bbc/sqs-consumer/issues/254

Which is to move aws-sdk to a peer dependency, which would make sense and allow users to have more control over the version in the future.
