### ISSUE TITLE
graceful reload using consumer.stop() 

### ISSUE THREAD

**Issue by skiod** [bbc/sqs-consumer#253]
I want to implement graceful reload like this :
 
1. Restart the server 
2. Stop polling
3. Finish the current jobs
4. Start polling

i checked the doc found this `consumer.stop()`
but it doesn't stop polling

Thanks in advance

**Comment by nicholasgriffintn** [comment]
Looks like this duplicates https://github.com/bbc/sqs-consumer/issues/234
