### ISSUE TITLE
No standoff on queue errors

### ISSUE THREAD

**Issue by eurostar-fennec-cooper** [bbc/sqs-consumer#273]
**Describe the bug**
If the queue does not actually exist, this error:
`{"name":"SQSError","code":"AWS.SimpleQueueService.NonExistentQueue","statusCode":404,"retryable":false,"time":"2021-09-01T12:53:04.983Z"}`
Is endless generated with no wait time in between retries. Not critical, but if errors are logged, it spams the logs/consumes a lot of resources attempting to retry immediately.

**To Reproduce**
Steps to reproduce the behaviour:
1. Construct a Consumer for a queue that does not exist
2. Add an event handler to the queue that logs the "error" event
3. Run code, error event handler is called endlessly filling up the logs and increasing CPU consumption by a huge margin

**Expected behaviour**

There should be a standoff in between retries for any error involving the queue whatsoever.

**screenshots**

**Additional context**
Add any other context about the problem here, such as specific device information.

**Comment by nicholasgriffintn** [comment]
So AWS returns the code `AWS.SimpleQueueService.NonExistentQueue` for this error, so we could definitely make a change to the `isConnectionError` function to also listen for this code, if this is true, then polling will not occur again until the value of `authenticationErrorTimeout`, so it will trigger again, but not until that timeout, which is 10s by default.
