### ISSUE TITLE
Not working with current (oct 2021) latest @aws-sdk/client-sqs without aws-sdk peerDependencies

### ISSUE THREAD

**Issue by ahmadalibaloch** [bbc/sqs-consumer#278]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup a node server and use @aws-sdk/client-sqs
2. setup a consumer as in the sqs-consumer readme

**Expected behaviour**
It should register a consumer as is default be

**Additional context**
New v3 aws sdk is moduler. sqs-consumer should be using latest sdk

**Comment by nicholasgriffintn** [comment]
this is the same issue as this: https://github.com/bbc/sqs-consumer/issues/251
