### ISSUE TITLE
Add support for large message production/consumption

### ISSUE THREAD

**Issue by nik-suri** [bbc/sqs-consumer#291]
**The problem**
Amazon SQS can only support messages up to 256KB in size. To handle large messages (up to 2GB), the AWS docs recommend using their [Extended Java Client Library](https://github.com/awslabs/amazon-sqs-java-extended-client-lib) which supports pushing/pulling large messages through S3.

**Suggested solution**
Enhance message consumption and deletion (and message production in https://github.com/bbc/sqs-producer) to use Node.js equivalents of the official implementation in the [AWS Extended Java Client Library](https://github.com/awslabs/amazon-sqs-java-extended-client-lib).

**Alternatives considered**
I've considered implementing the logic myself. However it's a bit messier since your libraries do not provide the capability to overwrite the deletion logic (in sqs-consumer) and the production logic (in sqs-producer).

**Additional context**
Should be a pretty simple implementation that can follow the same exact logic that is used in the [Extended Java Client Library](https://github.com/awslabs/amazon-sqs-java-extended-client-lib).

**Comment by nicholasgriffintn** [comment]
I don't think we are looking to extend the capabilities of this that far yet.

Contributions are welcome though :)
