### ISSUE TITLE
AssumeRoleWithWebIdentity authentication does not work 

### ISSUE THREAD

**Issue by fiatfilip** [bbc/sqs-consumer#292]
**Describe the bug**
If the AWS credential are missing, but the AWS_WEB_IDENTITY_TOKEN_FILE is present there seems to get an access denied error.
The application is deployed with Kubernetes and the serviceAccount has a IAM role which has attached a IAM policy with all the actions assigned on a specified queue.

**To Reproduce**
Steps to reproduce the behaviour:
1. The service account is created like described in https://docs.aws.amazon.com/eks/latest/userguide/enable-iam-roles-for-service-accounts.html
1. Within the pod start the consumer
2. AWS credential are not defined, but the AWS_WEB_IDENTITY_TOKEN_FILE env var is present
3. The following error occurs
`error: uncaughtException: SQS receive message failed: Access to the resource https://sqs.eu-central-1.amazonaws.com/ is denied.
SQSError: SQS receive message failed: Access to the resource https://sqs.eu-central-1.amazonaws.com/ is denied.
    at toSQSError (/home/[user]/[project-name]/node_modules/sqs-consumer/dist/consumer.js:45:22)
    at Consumer.receiveMessage (/home/[user]/[project-name]/node_modules/sqs-consumer/dist/consumer.js:155:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Expected behaviour**
The authenticated call should be performed and the message should be read.

**Comment by xpolb01** [comment]
Having the same issue

**Comment by nicholasgriffintn** [comment]
In my quick research, there doesn't look like there's any specific reason why this would not work with this library if used and implemented correctly.

Looking at the docs, `AssumeRoleWithWebIdentity` will return credentials:

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sqs/interfaces/assumerolewithwebidentitycommandoutput.html#credentials

This credentials will need to passed to SQS Consumer as described here:

https://github.com/bbc/sqs-consumer#credentials

If they are not working then this is something to do with your AWS setup, or AWS itself, which we do not support.

I'm going to close this issue on that basis.
