### ISSUE TITLE
Block message deletion once the handler function has completed successfully.

### ISSUE THREAD

**Issue by rafaelpolonio92** [bbc/sqs-consumer#294]
Is there any flag or any way that i can block this message deletion after the handler has completed succesfully?
I'm building a slack bot that has a "Delete Message" button. The handler is an interactivity that  sends a message to slack with three buttons.
The logic of those buttons are outside the handler, and i don't want to insert it .. so that's why i'm asking

**Comment by Chasty** [comment]
I also don't want to delete the message after the function has completed. so two or more different application can use that message as well.

**Comment by eranelbaz** [comment]
I have open PR to enable that #287
Hope they will merge it

**Comment by vaughandroid** [comment]
@memsb I think this can be closed now as @eranelbaz's PR got merged into the 5.7.0 release. :)

**Comment by memsb** [comment]
Thank you for bringing this to my attention. :)
