### ISSUE TITLE
ECONNRESET after consuming all messages

### ISSUE THREAD

**Issue by fr-kshibata** [bbc/sqs-consumer#30]
I'm getting [Error: socket hang up] code: 'ECONNRESET', body: {}
after I consumed all the message, how do I prevent this error?

**Comment by robinjmurphy** [comment]
Hi @fr-kshibata are you able to share the code you're using to consume the messages?

**Comment by fr-kshibata** [comment]
```
var app = Consumer.create({
			queueUrl: sqs.url,
			handleMessage: function (message, done) {
				var poster = formatString(message);
				console.log(poster);
				poster = JSON.parse(poster).Body;

				client.post('/sqs/', poster, function (err, req, res, obj) {
                    
                if(err)
                 callback(err,null);
					else {
						console.log(obj);
					}
				});

				done();
			},

			sqs: new AWS.SQS()
		});

		app.on('error', function (err) {
			callback(err.message, null);
		});

		app.start();
	
```

**Comment by fr-kshibata** [comment]
I think the problem is sqs consumer sends an error if there is no more sqs message that can be received, but since this code is called by the restify.createJsonClient, then it still works even though there is no more message to be received

**Comment by robinjmurphy** [comment]
Can you show me where the `callback` variable comes from in that code?

Is that entire block running inside a function?

You really only want to have one consumer in your application. The `error` event shouldn't be connected to a particular callback, otherwise you risk that callback being called twice.

The client doesn't send an error if there are no more messages on the queue. It just sits and keeps polling.

**Comment by fr-kshibata** [comment]
```
var client = restify.createJsonClient({
	url: 'http://localhost:8080'
});

console.log(client.url.href);


sqsFunction(client, aws, sqs, function (err,req,res,obj) {
	if (err)
		console.log(err.message);

});
```

**Comment by fr-kshibata** [comment]
I removed the `if(err) callback(err,null)` and looks like its ok now

thanks @robinjmurphy
