### ISSUE TITLE
How to consume next sqs message after server response

### ISSUE THREAD

**Issue by fr-kshibata** [bbc/sqs-consumer#31]
I have an sqs-consumer inside a restify.createJsonclient, which calls a restify server, 

How do I make it such that sqs-consumer will wait for server response before consuming another sqs message?

 Code is same as #30

**Comment by robinjmurphy** [comment]
Hi @fr-kshibata you shouldn't call `done` until you're finished processing a message, which in your case is when you receive a response.

Here's an example with request:

```js
var Consumer = require('sqs-consumer');

var request = require('request');

var app = Consumer.create({
  queueUrl: 'https://sqs.eu-west-1.amazonaws.com/account-id/queue-name',
  handleMessage: function (message, done) {
    request('http://www.example.com', function (err) {
      done(err);
    });
  }
});

app.on('error', function (err) {
  console.log(err.message);
});

app.start();
```

**Comment by robinjmurphy** [comment]
Your consumer won't pick up another message by default until `done` is called.

**Comment by fr-kshibata** [comment]
Thanks @robinjmurphy
