### ISSUE TITLE
Is this package abandonned?

### ISSUE THREAD

**Issue by PierreRambaud** [bbc/sqs-consumer#310]
**Question**
Regarding what happened on the Pull requests list and also on the issues, are people from the organization planning to update this repository?

If not, are you planning to add maintainers in order to make it work for the v3?

You did a great work with it, I'm pretty sure some people from the community would be ok to help you to maintain it :)

**Comment by giacomomagini** [comment]
I was about to ask if there's any plan to migrate aws-sdk to v3. I'd be happy to help!

**Comment by PierreRambaud** [comment]
@giacomomagini There is a fork available https://github.com/rxfork/sqs-consumer which is working with the v3

**Comment by ThatAnonyG** [comment]
Is this thing dead or what. This is one of the major concerns with NodeJS. Thousands of projects relies on this package and seems like the author just abandoned without any notice.

**Comment by PierreRambaud** [comment]
I think we can conclude this repository is dead :eyes:

**Comment by nicholasgriffintn** [comment]
It's not dead no. We're working on it :)

We're happy to take a look at any PRs if you have any :)

We've just updated the documentation and CI to make it easier to contribute and we're looking at updating the dependencies shortly.

After that, we'll be able to look at supporting v3.

Apologies for any delay.
