### ISSUE TITLE
SQSError does not properly inherit from Error and has no stack trace.

### ISSUE THREAD

**Issue by cybersam** [bbc/sqs-consumer#32]
SQSError objects apparently are intended to inherit from Error (since they use the Error prototype), but I was surprised to find that they have no stack trace.

To properly inherit from Error, this code:

    function SQSError(message) {
      this.name = 'SQSError';
      this.message = (message || '');
    }
    SQSError.prototype = Error.prototype;

should be:

    function SQSError(message) {
      Error.captureStackTrace(this, this.constructor);
      this.name = this.constructor.name;
      this.message = (message || '');
    }
    util.inherits(SQSError, Error);

**Comment by nspragg** [comment]
fixed in v3.1.3
