### ISSUE TITLE
Release for 6.0.0 has no build

### ISSUE THREAD

**Issue by AlexBroadbent** [bbc/sqs-consumer#333]
**Describe the bug**

Importing `6.0.0` does not work when importing `sqs-consumer`.

**To Reproduce**
Steps to reproduce the behaviour:

2. Select '....'

**Expected behaviour**

**screenshots**

<img width="1177" alt="Screenshot 2022-12-16 at 17 27 58" src="https://user-images.githubusercontent.com/3311606/208154771-059ebf3a-9e2f-4809-a5ae-3b5bd6cc06a1.png">

**Additional context**

Reverting to `6.0.0-alpha.2` fixes the issue

**Comment by nicholasgriffintn** [comment]
Looking into this now

**Comment by nicholasgriffintn** [comment]
This should be resolved in `6.0.2` now, apologies for that, the issue was that we were still using `prepublish` instead of `prepare`, sorry, I didn't notice that.
