### ISSUE TITLE
[Bug]: Types broken in latest version

### ISSUE THREAD

**Issue by ChrisCates** [bbc/sqs-consumer#338]
### Describe the bug

```typescript
.../node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
worker/process.ts:11:9 - error TS2739: Type 'SQS' is missing the following properties from type 'SQSClient': destroy, middlewareStack, send

11         sqs: SQS,
           ~~~

  node_modules/sqs-consumer/dist/consumer.d.ts:16:5
    16     sqs?: SQSClient;
           ~~~
    The expected type comes from property 'sqs' which is declared here on type 'ConsumerOptions'

```

### Your minimal, reproducible example

...

### Steps to reproduce

...

### Expected behavior

...

### How often does this bug happen?

None

### Platform

...

### Package version

...

### Additional context

Can you not have this ridiculous churn in your Github repos.
It doesn't help and it turns me off so much, I'd rather just rewrite your library myself.

**Comment by nicholasgriffintn** [comment]
sqs-consumer now uses [AWS SDK V3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-sqs/index.html) and so the type for SQS has been changed to `SQSClient`, the error you provided is actually coming from code outside of sqs-consumer `worker/process.ts:11:9`.

I don't think there's an issue on our end here, if you prefer to use AWS SDK V2 then please use version `5.8.0`.

**Comment by ChrisCates** [comment]
Got it thanks @nicholasgriffintn.
I just noticed the README was updated.

Apologies for opening a redundant issue.

**Comment by nicholasgriffintn** [comment]
No problem, sorry it was not clearer for you.
