### ISSUE TITLE
[Bug]: Not change visibility timeout error failed messages when process message batch

### ISSUE THREAD

**Issue by doonpy** [bbc/sqs-consumer#350]
### Describe the bug

When processing the message batch, the `processMessageBatch` method does not change visibility timeout process failed messages (when `terminateVisibilityTimeout` is true)

### Your minimal, reproducible example

...

### Steps to reproduce

For example, I consuming batch 10 messages with `handleMessageBatch` is:
```typescript
for (const message of messages) {
    if (message.Body) {
       await handle(JSON.parse(message.Body);
    }
}
```

Simulate it:
```
- Message 1: Success
- Message 2: Success
- Message 3: Failed -> throw an error
```

Current behavior:
Not change the visibility timeout message from 3 to 10

### Expected behavior

- Visibility timeout of message 3 to 10 should be changed to 0

### How often does this bug happen?

None

### Platform

...

### Package version

v6.1.0

**Comment by nicholasgriffintn** [comment]
I'm not really sure that I understand what you are saying, but looking at the code, `changeVisibilityTimeoutBatch` should be called whenever any error occurs within the process message batch functionality if `terminateVisibilityTimeout` is true.

If you are saying that this is not happening then this would have to be investigated as to why.

I'll add a help-wanted on this for others find the problem if I don't have the time to.

**Comment by nicholasgriffintn** [comment]
Still not sure what the issue is here, so I think we should close this issue, please reopen if some further clarification can be provided.
