### ISSUE TITLE
[Bug]: heartbeatInterval is not working as expected

### ISSUE THREAD

**Issue by rishi-aga** [bbc/sqs-consumer#376]
### Describe the bug

`heartbeatInterval` is not cleared for all the messages, this is causing error events after the message is successfully processed.

possible fix: https://github.com/bbc/sqs-consumer/pull/375/files

### Your minimal, reproducible example

See steps to reproduce.

### Steps to reproduce

1. Use `batchSize` > 1, set `heartbeatInterval` and `handleMessage` for processing the message.
2. Add 2 messages to your queue while the app is not running
3. start the app
4. app successfully processes both messages in parallel.
5. app only clears `heartbeatInterval` for one of the messages. For other messages, it emits:
```
"error": {
        "code": "InvalidParameterValue",
        "fault": "client",
        "name": "SQSError",
        "statusCode": 400,
        "time": "2023-03-16T14:54:53.367Z"
    }
```

### Expected behavior

It should not be emitting error events after the message is successfully processed.

### How often does this bug happen?

Every time

### Platform

- OS: Linus
- Node Version: 16

### Package version

^7.0.2

### AWS SDK version

^3.258.0

**Comment by nicholasgriffintn** [comment]
This definitely needs some sort of investigation as to why, we've not been made aware of any such issues.

**Comment by rishi-aga** [comment]
Thanks @nicholasgriffintn
