### ISSUE TITLE
Message type is not exposed

### ISSUE THREAD

**Issue by matehuszarik** [bbc/sqs-consumer#384]
### Describe the bug

AWS [Message](https://github.com/bbc/sqs-consumer/blob/main/src/types.ts#L1) type is not re-exported from the package.

Most of the functions (e.g.: [handleMessage](https://github.com/bbc/sqs-consumer/blob/main/src/types.ts#L95) operate with this type and it would be good to use it after installing sqs-consumer.

### Your minimal, reproducible example

-

### Steps to reproduce

-

### Expected behavior

As a user I'd like to provide type safety by importing `Message` type.
```
import { Message } from 'sqs-consumer'
```

### How often does this bug happen?

Every time

### Platform

- OS: macos
- Node: all version

### Package version

> v6.x.x

**Comment by nicholasgriffintn** [comment]
I'm not sure this is actually required, as you need to install sqs-client anyway, it's realistically not that different or better from doing this:

`import { Message } from '@aws-sdk/client-sqs';`

I'll have a think on it, we did used to do it, but that was when we were adjusting the type ourselves.

**Comment by matehuszarik** [comment]
> As of version 7 of npm, peer dependencies are also auto installed

Exactly, so I don't have to add `@aws-sdk/client-sqs` to dependencies separately and can not import the `Message` type. This is the problem I'd like to solve.

IMO sqs-consumer should either enforce the installation of `@aws-sdk/client-sqs` or re-export the `Message` type.

**Comment by nicholasgriffintn** [comment]
Well no, the use case of needing the Message type is not that great (we haven't been exporting it for about half a year).

I'm not sure that it's that big of an ask for the user to import it directly themselves honestly, it's not something we're ever going to modify.

This isn't a bug either btw, so I'm gonna change the labelling.

**Comment by nicholasgriffintn** [comment]
This has sort of been done in https://github.com/bbc/sqs-consumer/pull/385 I'm not happy with it though due to the docs issues.

Thinking about the time I have available, I'm going to decide not to do this, if anyone would still like to do this, feel free to open a new pr with the documentation fixed.
