### ISSUE TITLE
[Bug]: Event listener on .once is called multiple times

### ISSUE THREAD

**Issue by schaeferto** [bbc/sqs-consumer#393]
### Describe the bug

When registering an event listener on a new consumer object using `.once()`, this listener is called multiple times.

### Your minimal, reproducible example

https://stackblitz.com/edit/nestjs-typescript-starter-agfsxk?file=src/app.controller.ts

### Steps to reproduce

Watch the console log statements.

### Expected behavior

The event listener should only be called once.

### How often does this bug happen?

Every time

### Platform

- OS: mac
- node: 16.7

### Package version

v7.0.3

### AWS SDK version

v3.316.0

**Comment by nicholasgriffintn** [comment]
Thanks for the issue and the reproduction, super helpful.

I'll take a look into this and get back the reason this might be happening.

**Comment by schaeferto** [comment]
Perfect. Thanks for your help!

**Comment by nicholasgriffintn** [comment]
This has been resolved in `[7.1.0-canary.2](https://www.npmjs.com/package/sqs-consumer/v/7.1.0-canary.2)`:

https://stackblitz.com/edit/nestjs-typescript-starter-e4tyij?file=package.json

I don't know when `7.1.0` will be fully released, but the plan is to finish up just a couple more bits and then it will be released, the canary version should be perfectly fine to use in the meantime if this is an important issue for you.
