### ISSUE TITLE
Inaccessible host: sqs.eu-central-1.amazonaws.com

### ISSUE THREAD

**Issue by james075** [bbc/sqs-consumer#4]
Hi, 

I got this issue when I perform massive sending / treating messages, have you any idea where it could come from?

![screen shot 2015-06-23 at 10 12 50 pm](https://cloud.githubusercontent.com/assets/5047120/8316094/040d95e0-19f5-11e5-9871-e24d02c2304a.png)

I also go this error message from aws: `This service may not be available in the 'eu-central-1' region` but I'm certain that sqs is available in eu-central-1 region..

**Comment by robinjmurphy** [comment]
Hi @james075. Which version of Node and which OS are you using? I'll see if I can reproduce this today.

**Comment by james075** [comment]
Hi @robinjmurphy, thank you for your concern, I don't have this error anymore.
It came from an intern issue I had with aws.

**Comment by james075** [comment]
Unfortunately, I this have this error, on massive message treatment..

@robincavalier I'm using node js v0.10.33 and OS X Yosemite 10.10.3

**Comment by james075** [comment]
plus, sometimes I got delete, sometimes receive errors:

```
[Error: SQS delete message failed: Inaccessible host: `sqs.eu-central-1.amazonaws.com'. This service may not be available in the `eu-central-1' region.]
[Error: SQS delete message failed: Inaccessible host: `sqs.eu-central-1.amazonaws.com'. This service may not be available in the `eu-central-1' region.]
[Error: SQS receive message failed: Inaccessible host: `sqs.eu-central-1.amazonaws.com'. This service may not be available in the `eu-central-1' region.]
```

**Comment by james075** [comment]
UPDATE 2:

when I restart the server, sqs will reconnecting fine but still don't know why I got this error
