### ISSUE TITLE
document effects of done(err) in regard to visibilityTimeout

### ISSUE THREAD

**Issue by edeliu2000** [bbc/sqs-consumer#40]
Looks like when calling done(err) on a processing error the message becomes visible immediately again whatever the configured visibilityTimeout is. That means the message becomes available again immediately and will get consumed again by other consumers (potentially from other instances) so unless the application handles an error differently, calling done(err) will cause immediate retrying. 

I think it should be documented more clearly what the effects of done(err) are and how it affects retries etc.

**Comment by robinjmurphy** [comment]
Hello @edeliu2000. The current documentation says:

> Calling done(err) with an error object will cause the message to be left on the queue. An SQS redrive policy can be used to move messages that cannot be processed to a dead letter queue.

We recommend using a redrive policy to move messages to a dead letter queue after a number of attempts.

Any ideas on how best we could improve this? Would welcome a PR.

**Comment by robinjmurphy** [comment]
Closing this issue. PR welcome on any improved documentation around the error behaviour.
