### ISSUE TITLE
[Bug]: TypeError: Cannot set property message of [object Object] which has only a getter

### ISSUE THREAD

**Issue by elmeister** [bbc/sqs-consumer#402]
### Describe the bug

Hello

Some errors do not allow to reassign their message (i.e. ZodError), which leads to an error [here](https://github.com/bbc/sqs-consumer/blob/87fd29912ad66fe4cfbb05e1318d16ee1dab25df/src/consumer.ts#L437-L440)
```
TypeError: Cannot set property message of [object Object] which has only a getter
```
So the original error is lost and only the one above is displayed

### Your minimal, reproducible example

Not provided

### Steps to reproduce

Not needed

### Expected behavior

Expected behavior is to see original error or to have more information about it

### How often does this bug happen?

Every time

### Platform

All Node versions affected

### Package version

7.1.0

**Comment by nicholasgriffintn** [comment]
I don't have a clue what you're talking about honestly, please provide more detail with some sort of reproducible example, without that, we can't help you.

**Comment by elmeister** [comment]
Ok, so here's the [zod](https://github.com/colinhacks/zod) library, which is pretty popular

Here is their [ZodError](https://github.com/colinhacks/zod/blob/0a17340e9fc4b909d10ca3687b6bc6454903ff21/src/ZodError.ts#L272-L274) implementation

For the minimal reproducible example, here's the error class with the sane idea as in ZodError:

```ts
class CustomError extends Error {
  issues: string[]

  constructor(issues: string[]) {
    super()

    this.issues = issues
  }

  get message() {
    return JSON.stringify(this.issues, null, 2)
  }
}
```

Now if within the `handleMessage()` the error above will be thrown
```ts
const error = new CustomError(['issue1', 'issue2'])
```

It will fail [here](https://github.com/bbc/sqs-consumer/blob/87fd29912ad66fe4cfbb05e1318d16ee1dab25df/src/consumer.ts#L437-L440)
In this `consumer.ts` lines of code
```ts
err.message =
  err instanceof TimeoutError
    ? `Message handler timed out after ${this.handleMessageTimeout}ms: Operation timed out.`
    : `Unexpected message handler failure: ${err.message}`;
```

So instead of "Unexpected message handler" we will receive only the error from `consumer.ts`

```
TypeError: Cannot set property message of [object Object] which has only a getter
```

**Comment by nicholasgriffintn** [comment]
Ahh I see so you're throwing a zod error and that is causing sqs-consumer to error.

Probably not an issue with sqs consumer itself but with the reformatting of the error from zod that was thrown.

One that'll need investigation.

**Comment by elmeister** [comment]
Zod package is commonly used to validate and add types to unknown data, which perfectly fits for SQS message body, and Zod throws its own error with getter for `message`, when data was not valid. 
The issue is manageable by adding try/catch wrapper for the `handleMessage()`callback content.

**Comment by nicholasgriffintn** [comment]
Sorry not sure I explained well enough, but basically, I know what zod is, the issue here is that the error sent has a property that is only a get, which means that sqs-consumer is unable to edit the message property itself.

This removes its ability to adjust the message property and thus offer its own error functionality, you're basically overwriting that ability with this implementation.

The error being outputted is correct and is actually on your app's side, and isn't a bug with sqs-consumer itself.

**Comment by elmeister** [comment]
I do not overwrite that ability in my app, it's how zod's `parse()` method works.
But anyways, closing this.
