### ISSUE TITLE
v5.8.0 if send message to sqs queue on other pc

### ISSUE THREAD

**Issue by geetee24** [bbc/sqs-consumer#450]
### Describe the bug

1. v5.8.0 if send message to sqs queue on other pc.
2. then start consumer.create(), it takes a 30 seconds exactly for the lib to get the first sqs message.  Subsequent messages arrive in 1 second.
why the 30 second delay?

### Your minimal, reproducible example

no link

### Steps to reproduce

1. v5.8.0 if send message to sqs queue on other pc.
2. then start consumer.create(), it takes a 30 seconds exactly for the lib to get the first sqs message.  Subsequent messages arrive in 1 second.
why the 30 second delay?

### Expected behavior

1st message should arrive in 30 seconds

### How often does this bug happen?

Every time

### Screenshots or Videos

none

### Platform

windows

### Package version

5.8.0

### AWS SDK version

v2

### Additional context

none

**Comment by nicholasgriffintn** [comment]
Without a reproduction, nothing can be done here, but also, this library isn't supporting past 5.8.0 anymore as we have moved to the v3 SDK.

Feel free to open a discussion if you'd like to discuss further, but this is not something we can handle in the issues.
