### ISSUE TITLE
[Bug]: ApproximateReceiveCount is not part of QueueAttributeName

### ISSUE THREAD

**Issue by sosafe-anas-bakro** [bbc/sqs-consumer#451]
### Describe the bug

Lint is complaining that ApproximateReceiveCount does not exist when setting `attributeNames` in `Consumer.create`  as QueueAttributeName doesn't have it.

Previous versions it was a string so we didn't have issues, I guess someone forgot it. 

### Your minimal, reproducible example

Too small to create an example

### Steps to reproduce

Try to fill out `attributeNames` in `Consumer.create` with [`ApproximateReceiveCount`] value, lint will complain __

### Expected behavior

Lint shouldn't complain, the type QueueAttributeName should contain ApproximateReceiveCountshouldn't

### How often does this bug happen?

None

### Platform

- All

### Package version

8.1.3

**Comment by nicholasgriffintn** [comment]
This takes the type from the AWS SDK, so they define what is correct here.

The comment here should probably be updated: https://github.com/bbc/sqs-consumer/blob/main/src/types.ts#L10

To change the example to simply link here: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-sqs/Variable/QueueAttributeName/

But aside from that, this isn't a bug.

**Comment by sosafe-anas-bakro** [comment]
Thanks @nicholasgriffintn, I added a comment here https://github.com/aws/aws-sdk-js-v3/issues/5671, once fixed I guess the library needs to use the latest version of AWS SDK.
