### ISSUE TITLE
Calling "done(message)" in order to remove a specific message from the queue

### ISSUE THREAD

**Issue by teckays** [bbc/sqs-consumer#48]
Currently the functionality is tied to the 10 batch queue offered by SQS, but what if I want to have one more layer of queue buffering keeping in mind that 10 is a quite small batch. Let's say i want to process queues in batches of 500

```
const queue = Consumer.create({
  queueUrl: '...',
  handleMessage: (message, done) => {
    someBuffer.push(message)

    if (someBuffer.length === 500) {
      // process all messages
      process(someBuffer, done)
    }
  }
})
```

```
process(buffer, done) {
  buffer.forEach(message => {
    // do something
    done(message.ReceiptHandle)
  })
}
```

Currently this is not possible because the `done()` callback is called against the message hitting the `handleMessage` function, they can't be "stored for later processing".

**Comment by robinjmurphy** [comment]
Hi @teckays. This is an interesting one.

If I've understood correctly you're trying to use an internal buffer to pull in larger batches than SQS currently allows you to?

Have you tried using the SQS library directly to do this?

**Comment by nspragg** [comment]
Closing issue due to inactively. Can reopen, if further discussion is required.
