### ISSUE TITLE
[Bug]: attributeNames does not support MessageSystemAttributeName

### ISSUE THREAD

**Issue by leovvay** [bbc/sqs-consumer#486]
### Describe the bug

currently attributes name have a type definition of QueueAttributeName https://github.com/bbc/sqs-consumer/blob/main/src/types.ts#L15C3-L15C17, and missing MessageSystemAttributeName from clinet-sqs, which is actually supported by attributeNames with ` attributeNames: ['MessageGroupId', 'SentTimestamp'] as any`, bypass

### Your minimal, reproducible example

Consumer.create with attributeNames: ['MessageGroupId', 'SentTimestamp'] 

### Steps to reproduce

1. create a consumer via Consumer.create with attributeNames: ['MessageGroupId', 'SentTimestamp'] 
2. observer type error
3. change to attributeNames: ['MessageGroupId', 'SentTimestamp'] as any
4. observer  MessageGroupId actually received with this attribute names

### Expected behavior

attributeNames type should support MessageSystemAttributeName from @aws-sdk/client-sqs

### How often does this bug happen?

None

### Platform

 macOs 14.4.1

### Package version

v9.1.0

### AWS SDK version

  "@aws-sdk/client-sqs": "^3.556.0",

**Comment by nicholasgriffintn** [comment]
AWS' SQS SDK sets the type for attributes as `QueueAttributeName` https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/sqs/command/ReceiveMessageCommand/.

So it should be updated their side as this is made to match what the SDK actually sets as its expectation.

**Comment by nicholasgriffintn** [comment]
Update: I've actually found a related issue here: https://github.com/aws/aws-sdk-js-v3/issues/5403 so that might be one to follow.
