### ISSUE TITLE
Multiple consumers for one queue

### ISSUE THREAD

**Issue by edeliu2000** [bbc/sqs-consumer#51]
There is a bug with running multiple consumers on one queue within the same process. Below a test I am running which gives very inconsistent results. In particular in regards to the effects of the done() call. Namely in case of multiple consumers a done() call like below looks to not have any effect, and to not delete the message. That means the queue items are processed ad infinitum, every time after the visibilityWindow expires. It looks like a major inhibition to run this library at proper scale. Just working with the batchSize=10 is too low. It means you can only run 10 messages in parallel per instance even if the logic is mostly async (It should be close to 500+/instance). The issue seems to be in the async.series() call in the libraries _processMessage function. It has something to do with the consumers being initialized and started in a normal (sync) for-loop. Its worth to see if it can get fixed by trying to start multiple consumers within an async loop

`
var SQSWorkers  = function(config){
   //initialization related stuff
   ...
  this.numberWorkers = 40;
  this.consumerWorkers = [];
  this._setup(config);   
}

SQSWorkers.prototype._setup = function(config){
    var self = this;
    for(var i=0; i<this.numberWorkers; i++){

        this.consumerWorkers[i] = Consumer.create({
            queueUrl: config.producerUrl,
            messageAttributeNames: ["retried"],
            handleMessage: function (message, done) {

                var notificationStart = Date.now();
                var messageBody = JSON.parse(message.Body);
                var retried = message.MessageAttributes && message.MessageAttributes.retried ? Number(message.MessageAttributes.retried.StringValue) : 0;
                var worker = this;

                logger.info("ConvertStoreConsumer start handling event from SQS worker:%s start:%s msgId:%s msg: %j", worker.workerName, notificationStart, message.MessageId, message, {});

                //processing the message happens on onEvent() 
                return self.onEvent(messageBody, function(err){

                    //on error message will be enqueued again for later retry 
                    //TODO add some logs on error and elaborate more 
                    if(err){
                        logger.error("ConvertStoreConsumer error on handling event from SQS. worker:%s error:%j msgId:%s retrying...", worker.workerName, err, message.MessageId, {});
                        return self._handleRetry(message.MessageId, message.Body, retried, function(){
                            return done();
                        });
                    }

                    //otherwise remove item from queue with done()
                    logger.info("ConvertStoreConsumer finished handling event from SQS worker:%s docid:%s tenant:%s v:%s dur:%s", worker.workerName, messageBody.id, messageBody.tenant, messageBody.v, Date.now() - notificationStart, {});
                    done();
                });
            }
        });

        this.consumerWorkers[i].workerName = "consumer-worker-" + i;        
        this.consumerWorkers[i].on('message_processed', function(message){

            //otherwise remove item from queue with done()
            logger.info("ConvertStoreConsumer message processing done - worker:%s msgId:%s", this.workerName, message.MessageId, Date.now(), {});

        });

    }
}

SQSWorkers.prototype.start = function(param){
    //start all workers
    if(this.consumerWorkers && this.consumerWorkers.length){
        this.consumerWorkers.forEach(function(worker, pos){
            worker.start();
        });
    }else{
        // just log an error here and don't throw an error to not break on local 
        logger.error("ConvertStoreConsumer not initialized for SQS. ConvertStoreConsumer cannot start.", {});
    }
}

SQSWorkers.prototype.onEvent = function(message, callback){
    //this is the application logic, basically what is supposed to happen with a message
    //Its mostly REST calls to other services
    ....

    if(err){
        return callback(err);
    }

    callback(null)

}
`

**Comment by nspragg** [comment]
We've not been able to reproduce this issue. Tested using the following script, varying the number of consumer instances and batchsize. After each test, all messages were dequeued. No errors. 

Test script:
```js
'use strict';

const Consumer = require('sqs-consumer');
const QUEUE = ''; // removed intentionally

function createConsumer() {
  return Consumer.create({
    queueUrl: QUEUE,
    batchSize: 1, 
    handleMessage: function (message, done) {
      console.log(message);
      done();
    }
  });
}

function startMultipleConsumers(n) {
  for (let i = 0; i < n; i++) {
    const consumer = createConsumer();
    consumer.on('error', function (err) {
      console.log(err.message);
    });
    consumer.start();
    console.log('started consumer...');
  }
}

// startMultipleConsumers(10);
// startMultipleConsumers(100);
startMultipleConsumers(1000);
```

**Comment by nspragg** [comment]
Closing issue - if further discussion is required, will reopen.

**Comment by unDemian** [comment]
I am having the same issue. @nspragg your example works ok. But I am using a collection to hold all created consumers so I can stop some of them similar to how @edeliu2000 is using an array. Even with 3 consumers for same queue and 1k messages the consumer gets crazy. 

- Some messages are not sent to the handler function even though consumed from the queue.
- Polling continues even though not all done were called so messages are overlapping.

I am not sure exactly what happens but my best guess is that it has something to do with the async series. Someone is messing the references for done or for the handleMessage if you save multiple consumers in an array or collection.

I was creating the objects in a loop then starting the consumers in another loop. I busted my head around this for several days now and I cannot understand what happens. I just used the logic in your example and it works fine but this means that I have no reference to created consumers and no control over stopping them.

**Comment by brandonmp** [comment]
@unDemian  had a similar use case. haven't tested extensively but so far this works. I took the snippet w/ the for loop and just added an `eventEmitter` in the upper scope to keep track of stuff

adapting previous example

```
'use strict';

const Consumer = require('sqs-consumer');
const QUEUE = ''; // removed intentionally

const events = require('events')
const killSignalEmitter = new events.EventEmitter()

function createConsumer() {
  return Consumer.create({
    queueUrl: QUEUE,
    batchSize: 1, 
    handleMessage: function (message, done) {
      console.log(message);
      done();
    }
  });
}

const startMultipleConsumers = (n) => {
    for (let i = 0; i < totalWorkers; i++) {
        const consumer = createConsumer()
        consumer.on('error', (err) => {
              console.error(err)
        })
        consumer.start()
        
        // listen for kill message from upper scope
        killSignalEmitter.on('killSwitch', () => {
            console.log("KILL RECEIVED")
            consumer.stop()
        })

        // notify upper scope that a worker has finished shutting down
        consumer.on('stopped', () => {
            console.log('Finished queue shutdown')
            killSignalEmitter.emit('workerDown')
        })
    }
}

var totalWorkers = 1000
var deadWorkers = 0 

// intercept kill signal and shutdown workers gracefully
process.on('SIGINT', () => {
    console.log('Starting queue shutdown')
    killSignalEmitter.emit('killSwitch')
})

// tally our casualties. when all workers have shuffled off mortal coil, shut her down
killSignalEmitter.on('workerDown', () => {
    deadWorkers++
    if (deadWorkers >= totalWorkers) process.exit(0)
})

startMultipleConsumers(totalWorkers);
```
