### ISSUE TITLE
[Bug]: cannot install from npm 

### ISSUE THREAD

**Issue by piotrgregor** [bbc/sqs-consumer#528]
### Describe the bug

root@e30cf0dca7ba:/SRC/# cat package.json 
```
{
  "dependencies": {
    "sqs-consumer": "^5.8.0"
  },
  "name": "consumer1",
  "version": "1.0.0",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": ""
}
```
root@e30cf0dca7ba:/SRC/# npm i
```
(node:22) ExperimentalWarning: CommonJS module /usr/local/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /usr/local/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/sqs-consumer - Not found
npm error 404
npm error 404  'sqs-consumer@^5.8.0' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
```

### Your minimal, reproducible example

npm i sqs-consumer

### Steps to reproduce

`npm install sqs-consumer`

### Expected behavior

Installed from npm

### How often does this bug happen?

Every time

### Screenshots or Videos
<img width="401" alt="Screenshot 2024-12-08 at 20 00 40" src="https://github.com/user-attachments/assets/e1518c15-bcde-422e-afbc-a37bba423ba1">

_No response_

### Platform

linux debian buster

### Package version

latest

### Additional context

There may be actually more issues... It looks like the whole project CI/CD is broken at the moment 
<img width="978" alt="Screenshot 2024-12-08 at 20 13 37" src="https://github.com/user-attachments/assets/93fce1bd-97d1-46c5-930a-407c4a694c1a">

_No response_

**Comment by nicholasgriffintn** [comment]
This looks like an issue on your end or an issue with NPM services, potentially temporary.

We can't support NPM or connecting to it, however, it appears there was a scheduled change today: https://status.npmjs.org/.

**Comment by piotrgregor** [comment]
Yes, that was a fault on _npmjs_ caused by infra upgrade, it's back to normal now (functioning)
