### ISSUE TITLE
Read region from env vars

### ISSUE THREAD

**Issue by virtser** [bbc/sqs-consumer#55]
Today the region default value is hard coded:

```
  this.sqs = options.sqs || new AWS.SQS({
    region: options.region || 'eu-west-1'
  });
```
https://github.com/bbc/sqs-consumer/blob/master/index.js#L66

I suggest to read it from default **AWS_REGION** environment variable instead.
Like this:

```
  this.sqs = options.sqs || new AWS.SQS({
    region: options.region || process.env.AWS_REGION
  });
```

WDYT?
I can open pull request if you agree.

**Comment by robinjmurphy** [comment]
Hi @virtser. Is this not something that the AWS SDK does out of the box? If not I think we could include this.

**Comment by virtser** [comment]
Well, it is by default, but by providing this option override you don't use
it and use hard coded value instead. ;)

**Comment by robinjmurphy** [comment]
Got it.

This is the problem https://github.com/bbc/sqs-consumer/blob/master/index.js#L66.

If you'd like to submit a PR, can we go for:

```js
  this.sqs = options.sqs || new AWS.SQS({
    region: options.region || process.env.AWS_REGION || 'eu-west-1'
  });
```

This just means we can release a new minor version and not break anyone who was relying on the old default.

**Comment by virtser** [comment]
Sounds good.

**Comment by virtser** [comment]
@robinjmurphy I opened a PR

**Comment by virtser** [comment]
@robinjmurphy I opened a PR
