### ISSUE TITLE
Support Deleting Messages in Batch

### ISSUE THREAD

**Issue by jschell12** [bbc/sqs-consumer#6]
Have you considered  supporting the DeleteMessageBatch request for SQS?

FYI - Using this module to replace our own implementation so its nice to remove clunky code from our app as much as possible. Thanks for this.

**Comment by robinjmurphy** [comment]
Hi @jschell12. There's certainly an opportunity to delete batches of messages in one go but we haven't looked into it yet. We use the module with a `batchSize` of 10 in most of our projects and deleting the messages one-by-one hasn't proven a problem for us.

Are you just looking to optimize the number of delete requests when working with batches of messages?

**Comment by jschell12** [comment]
Optimization would be great but I could always fork this and implement it myself and submit a pull request if need be. The only issue batching delete requests solves is fewer requests to AWS. However, looking at the SQS pricing suggests that using SQS is so cheap that batching deletes really doesn't save you much; at least at our scale.

**Comment by robinjmurphy** [comment]
Would definitely welcome a PR to support batch deletes as every little helps. It might change the semantics of the events slightly (e.g. what if one delete fails, but the others succeed etc.) but let me know if you want any input on a PR.

**Comment by nspragg** [comment]
Closing issue as it's from Aug 2015. If you wish to discuss further, we can re-open.
