### ISSUE TITLE
Problem trying to consume on a specific date

### ISSUE THREAD

**Issue by JonathanGonczoroski** [bbc/sqs-consumer#60]
On day 14, between 07:00 a.m UTC and 10:00 a.m UTC, there was a problem consuming in a sqs queue.

I wonder if this kind of problem could happen. 

Code:

```
var consumer = require('sqs-consumer');

function createTrip() {
var app = consumer.create({
     queueUrl: config.createTrip,

     handleMessage: function(message, done) {
                   done();
      }
});

app.on('error', function(error) {
           console.log(error);
 });

app.start();
}
```

The code above is what you use to consume as messages from the queue. If you need more data, please ask!

**Comment by robinjmurphy** [comment]
Hi @JonathanGonczoroski. That looks pretty good to me.

What happened when it failed? Were there just no messages being processed or was there some kind of error?

**Comment by JonathanGonczoroski** [comment]
Just no messages being processed, so is not return error. Accumulated several messages, and suddenly consumed all, however this is a problem, because I need that's messages in real time.

**Comment by cejast** [comment]
Hi @JonathanGonczoroski

This doesn't seem like this is an issue with the library as your messages were eventually processed.

The nature of how SQS works means that messages won't always be processed instantaneously, the idea is that your messages will be processed _eventually_.
