### ISSUE TITLE
Retrieve the batchSize twice to prevent processing lock

### ISSUE THREAD

**Issue by nmussy** [bbc/sqs-consumer#61]
It seems like the consumer only retrieves `n` messages and doesn't do another SQS request before the `n` messages have been handled.

Would it be possible to add an option to retrieve `2n` messages? This would allow the consumer to have `n` messages being handled at all time, and not `[1-n]`. I realize that this would add another abstraction layer to the consumer, but it would potentially save a lot of execution time.

**Comment by robinjmurphy** [comment]
Hi @nmussy!

It's currently limited to 10 because we don't maintain an internal queue. You can get around this by spanning multiple consumers in the same or different processes.

I'd be interested to explore n > 10 as a feature though if you're up for contributing?

**Comment by nmussy** [comment]
Hello @robinjmurphy,

I was thinking of looking into it myself this week.
We can go into the specifics of the API later, but what do you think about having a `{handlers: n}` option? If that option is set, the queue will do its best to maintain that number of messages being handled, i.e. retrieve more messages than the `batchSize`, and do multiple batches if there are more than 10 handlers.

Have a nice day!

**Comment by robinjmurphy** [comment]
Thats sounds like a great start. There's some prior art here that might be worth considering also: https://github.com/TechnologyAdvice/Squiss.

**Comment by nmussy** [comment]
I didn't know about [TechnologyAdvice/Squiss](/TechnologyAdvice/Squiss), thanks.

I looked into your code, and it's very short and neat. You're sure you'd like to have this option implemented? I'm not trying to back out already, but something like a 25% in LOC  would "bog it down" a little. 😄 

I personally think it's a very useful feature, and it would have saved me 10% of paid and unused CPU on my EC2 instances.

**Comment by robinjmurphy** [comment]
I think we should see how it looks if you're up for spiking something out. It's a nice feature. If we can implement it cleanly then I think we should consider it.

**Comment by nspragg** [comment]
Closing this issue due to inactively. However, if you have a spike ready or wish to discuss this further, I'm happy to reopen.
