### ISSUE TITLE
Idea: delayAndReQueue or Expose the deleteMessage method and perhaps a delayMessage

### ISSUE THREAD

**Issue by zeroasterisk** [bbc/sqs-consumer#63]
Currently I do:
- `done()` which deletes a message when successful.
- `done(err)` which does nothing with a message, when it is not successful...

That causes the message to be re-polled and processed, until SQS moves the message to a dead letter queue... 

This is a great setup... But some of my messages, I know why and when they should be re-processed, I know they need to be delayed (on a schedule)...

It seems like, as an alternative to `done()` we could have a `delaySeconds(60)` which deletes the message and re-sends it with a `delaySeconds=60`

I know I could do this myself, with `sqs-producer` - but it seems a common and simple enough thing that building it in made sense.

thoughts?

_(also - thanks - this is an excellent set of libraries for getting started with SQS fast)_

**Comment by cejast** [comment]
I don't think this should be the responsibility of this library - really, this is what the DLQ is for. I would set up another consumer on the DLQ and re-send it that way.

**Comment by zeroasterisk** [comment]
Yup, consuming from the dead letter queue make sense. I suppose I was just trying to "handle" some known failure cases more proactively, vs retrying X times every 30 seconds.
