### ISSUE TITLE
If isAuthenticationError is true then why try to connect again?

### ISSUE THREAD

**Issue by sooykoot** [bbc/sqs-consumer#65]
isAuthenticationError might return true because of 'CredentialsError'.

Does it even make sense to do - setTimeout(this._poll.bind(this), this.authenticationErrorTimeout);

If the Credentials are wrong it will always fail to connect to the queue. There is no point of trying to connect after every 10 seconds. So, in case of wrong credentials the service should exit instead of keep trying to connect to the queue.

**Comment by cejast** [comment]
Hi @sooykoot,

This is a valid issue, although it's worth noting that there should be differentiation between errors for incorrect credentials and misconfigured permissions.

If permissions are invalid, then there should be retries, as this is something that might not be specific to your code and can be fixed without code changes i.e. in the AWS console.

If credentials are incorrect or missing, then we shouldn't retry.

Would be happy to accept a PR for this.

**Comment by nicholasgriffintn** [comment]
Thinking about this, I don't think this is actually an issue, yes we probably want a retry after an authentication timeout, it also defaults to `10000` and that can be set yourself to be higher, so I don't think this is a huge issue or one to look at.
