### ISSUE TITLE
done(err) not working

### ISSUE THREAD

**Issue by sabper** [bbc/sqs-consumer#71]
hi! i'm use sqs-consumer.

it is great npm for AWS SQS. thank you.

my handlemessage fucntion write promise chain.

```
    findOrder()
    .then(pushToRider)
    .catch((err) => {
      logger.error('catch error', err)
      done(err) // or i'm try return done(err)
    })

```

i want left message from queue when occured error with promise chain.
and error message is move dead letter queue by redrive sqs policy.

but occured promise error when occured promise catch error.

```
10|bsqs    | (node:66103) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Callback was already called.
```

why this error occured???

thank you.

**Comment by doggan** [comment]
Are you sure you're not calling `done` twice? It's hard to tell without seeing the surrounding code.

Internally, sqs-consumer is using `async.series` to handle the done/error chain. `Error: Callback was already called.` is an exception thrown by async when the `done` callback of `series` is called more than once.

**Comment by nspragg** [comment]
@sabper - I can't debug the small snippet of code you've provided (missing context). However, by looking at the error message, you need to ensure you're only calling `done` once.
