### ISSUE TITLE
done(err) leaves messages in-flight

### ISSUE THREAD

**Issue by rocketspacer** [bbc/sqs-consumer#72]
Messages after being left on queue with done(err) still have to wait for their visibility timeout to expires. I want to add feature for terminating message's visibility timeout. Are you guys accepting pull request?

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#terminating-message-visibility-timeout

**Comment by nspragg** [comment]
Hi @rocketspacer. What is your specific use case for this feature?

**Comment by rocketspacer** [comment]
@nspragg I have a consumer polling a queue. Due to the nature of the task, I can't estimate the time it takes to process a message, so I set the visibility timeout to a large number.

Each time a task fail, I want the message to be left on the queue for retrying (before pushing to dead-letter-q), but due to high visibility timeout, the retry will happen very much later.

It's even worse if I'm using a FIFO, that's like a stuck job if you don't terminate visibility timeout.

**Comment by nspragg** [comment]
In an error state (with a large timeout) it sounds like it could be useful to terminate the visibility timeout early. 

Are you considering making a call to `sqs.changeMessageVisibility()` when a processing error occurs? i.e:
https://github.com/bbc/sqs-consumer/blob/master/index.js#L163

**Comment by rocketspacer** [comment]
Yes, but I think we should make it optional so it's not a breaking change

**Comment by nspragg** [comment]
@rocketspacer - v3.6.0 released. Thanks.
