### ISSUE TITLE
does not gracefully handle thrown errors in handle message

### ISSUE THREAD

**Issue by trashhalo** [bbc/sqs-consumer#78]
We use this library all over the place at work and every handleMessage we write has to `Promise.try(() =>` because sqs-consumer doesnt catch errors causing the consumer to fall over on the first thrown exception. 

I think thats a surprising behavior. I suggest adding a try/catch that calls done(error) if a error bubbles up that far.

**Comment by nspragg** [comment]
Sorry about the delay in replying. Yes, I agree, we could improve exception handling. Will patch this. 

Out of interest, what unhandled exceptions are you seeing? Parsing errors?

**Comment by trashhalo** [comment]
99% of the time its JSON.parse()

**Comment by niklasR** [comment]
@trashhalo I can't help with the `JSON.parse`, but for the other 1% we use `[_.get](https://lodash.com/docs/4.17.4#get)` to help with that.

**Comment by alexlydiate** [comment]
This still seems to be the case, unless I'm missing something, even though the documentation does say "Throwing an error (or returning a rejected promise) from the handler function will cause the message to be left on the queue."

Whereas, I throw an error, the message is deleted from the queue and the program falls over.

**Comment by niklasR** [comment]
Hi @alexlydiate, 
Is that on v4?

**Comment by alexlydiate** [comment]
Hi @niklasR - false alarm, my fault entirely, throwing the error in the wrong place. Great library, working lovely :)
