### ISSUE TITLE
Doubt about order of messages consumed

### ISSUE THREAD

**Issue by JonathanGonczoroski** [bbc/sqs-consumer#79]
Hi, if you enter 10 messages in sqs. One every millisecond. The order that the sqs-consumer consumes the messages and in the order in which they were inserted?

**Comment by nspragg** [comment]
If you want to retain message order, you need to use a FIFO queue. Standard queues don't guarantee message order. 

See docs:
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html
