### ISSUE TITLE
Workers stop processing messages

### ISSUE THREAD

**Issue by seanlindo** [bbc/sqs-consumer#82]
Would appreciate some help in figuring out this issue. I'm running 7 workers in parallel using `pm2`. After a few minutes, only one worker continues to process messages. A few minutes after that, no workers are receiving messages. `Message Received` and `Message Processed` are printed by all workers, then just a few workers, then one, and then none. 

Here are my settings and relevant code.

## Queue Settings

**Default Visibility Timeout**: 90 seconds
**Message Retention Period**: 4 days
**Maximum Message Size**: 256kb
**Delivery Delay**: 0s
**Receive Message Wait Time**: 10s

## Code
    import 'babel-polyfill'

    /** Libraries */
    import SQSConsumer from 'sqs-consumer'
    import serializeError from 'serialize-error'

    /** Internal */
    import IndexingService from './services/indexing.service'
    import logger from './utilities/logger'
    import ravenClient from './utilities/raven'

    const indexingService = new IndexingService()

    const startProcess = async () => {
        const app = SQSConsumer.create({
            queueUrl: 'https://sqs.us-east-1.amazonaws.com/your-queue-here',
            waitTimeSeconds: 5,
            visibilityTimeout: 90,
            handleMessage: async (message, done) => {
                try {
                    const parsedBody = JSON.parse(message.Body)
                    await indexingService.startProcess(parsedBody)

                    done()
                }
                catch (e) {
                    logger.error({
                        'Error': serializeError(e)
                    })

                    if(process.env.NODE_ENV == 'production') {
                        //ravenClient.captureException(e)
                    }

                    done(e)
                }
            }
        })

        app.on('error', (e) => {
            logger.error({
                'Error': serializeError(e)
            })

            console.log(e);
        });

        app.on('processing_error', (e, message) => {
            logger.error({
                'Error': serializeError(e)
            })

            console.log(message);
        });

        app.on('stopped', () => {
            console.log('Worker Stopped.');
        });

        app.on('message_received', () => {
            console.log('Message Received.');
        });

        app.on('message_processed', () => {
            console.log('Message Processed.');
        });

        app.start()
    }

    startProcess()

**Comment by seanlindo** [comment]
Edit: I tried raising my default visibility to 90 seconds in SQS and added this setting to the config object above under suspicion that my process might be taking too long. Workers are still slowly dropping out of the pool.

**Comment by seanlindo** [comment]
One more thing to add, I have another service running on a quad-core server with only 3 workers (n-1) and it's been running for days with no issues. 

My Mid 2014 2.2 GHz Intel Core i7 reports 8 cores when I use the `sysctl -n hw.ncpu` command, hence my decision to use 7 workers. Perhaps I should only be running 3, since I have 4 physical cores?

**Comment by cejast** [comment]
Can you provide more information? How many messages are left on the queue? Are you seeing any error messages?

The fact that messages are being processed at the start tells me that something is being blocked. We also haven't tested `sqs-consumer` with async/await so we can't guarantee the behaviour here yet.

**Comment by seanlindo** [comment]
There are no error messages, and I have 8,395 messages in the queue. I've used this library in a similar pattern for months now with no issues at all, so I'm curious what it could be that's causing problems all of a sudden. 

If it's of interest, I'm simply querying my database, creating objects, and indexing them to Elasticsearch one at a time. 

It definitely appears like workers are getting messages, but something happens and they no longer process them (or it gets stuck).

**Comment by nspragg** [comment]
What specific version are you using?

**Comment by nspragg** [comment]
Ok, lets assume you're using v3.6.1. We've run tests using a modified version of the code you provided (stubbed IndexService and replaced import with require). Tests included using pm2 in cluster mode. 

We were not able to replicate the behaviour you've described (workers stopping). I would suggest focussing you attention on the IndexingService.

**Comment by alexdrans** [comment]
@seanlindo Did you ever fix this?

**Comment by seanlindo** [comment]
@alexdrans I ended up using RabbitMQ instead.

**Comment by guyisra** [comment]
this is happens for us as well. it works then suddenldy it doesn't
Are there any cases where it would stop working completely? (no errors, no nothing, and 50k message in the queue). Killing node and restarting it would fetch more message but then stop processing again. 
@nspragg any ideas?

**Comment by alexdrans** [comment]
@guyisra Without posting code it's hard to say, but it's quite likely that you're silently catching an error somewhere or something similar, and `done()` is not being called.

**Comment by guyisra** [comment]
Yup that was the issue, the handler threw and there was no done(error) called. Thanks!
