### ISSUE TITLE
Any tips? "SQSError: SQS delete message failed" / "The receipt handle has expired"

### ISSUE THREAD

**Issue by 26medias** [bbc/sqs-consumer#85]
Hi,

I get an exception thrown regularly, and can't find a way to fix the issue.

I'm hoping you have an idea about the cause?

I use FIFO queues, with the following settings:
![](https://i.imgur.com/hLFx8dN.png)

I then have my code to send/receive the messages:
```

	var queue	= {
		send:	function(payload, options) {
			options	= _.extend({
				group:	'',
				queue:	'scores'
			}, options);
			
			var sqsParams = {
				MessageBody:			JSON.stringify(payload),
				QueueUrl:				'https://sqs.us-east-2.amazonaws.com/'+ftl.options.aws.client.id+'/'+ftl.options.env+'-'+options.queue+'.fifo'
			};
			sqsParams.MessageDeduplicationId	= options.id;
			sqsParams.MessageGroupId			= options.group;
			sqs.sendMessage(sqsParams, function(err, data) {});
		},
		getHandler:	function(name, callback) {
			return Consumer.create({
				region:				'us-east-2',	// OHIO, to get FIFO queues
				queueUrl:			'https://sqs.us-east-2.amazonaws.com/'+ftl.options.aws.client.id+'/'+ftl.options.env+'-'+name+'.fifo',
				batchSize:			1,
				visibilityTimeout:	20,
				handleMessage:		callback,
				sqs:				new AWS.SQS()
			});
		}
	};
```

To send data I use:

```
	queue.send({
		uuid:		'xxxxx',
		session:	'yyyyy',
		race:		'zzzzz'
	}, {
		group:	'yyyyy',
		id:		'some-long-unique-id',
		queue:	'race-start'
	});
```

To listen I use:

```
	var scoreQueue			= queue.getHandler('race-start', function(message, done) {
		ftl.data.sessionv2.classic.processScore(JSON.parse(message.Body), done);
	});
```

It works for a while, then randomly triggers this:

```
SQSError: SQS delete message failed: Value AQEB3XwPqs1p3WOXYP12JIR33hxePQ/Amls5OXgY2yaj2CKkFM3CuEPXgAPw4KbUWAffCgsHezZJqOEIOyDOlX4JTg+ndrTW4xu4RDEC9PJy8KQvuHU7ALbtIOb9N4U2yIN9TJwWj+GkK9vNKUeC9ZJslgeG5QUS/Xj4x2tWICsbdldlexuuP+V06qixVL/n7Q/8Ws6/IEWD7awwPy2zUehe0eZ16FfpCESoPICehhy+cEn/pm3+a7X2aCV9vqhNpEoGvHnEGyVAdzlAhR82cm2ejQO+SJYtHdpWN4tgI8j5TU4= for parameter ReceiptHandle is invalid. Reason: The receipt handle has expired.
    at Response.<anonymous> (C:\xampp\htdocs\node-fw\node_modules\sqs-consumer\index.js:197:24)
    at Request.<anonymous> (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\request.js:364:18)
    at Request.callListeners (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\request.js:682:14)
    at Request.transition (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\request.js:684:12)
    at Request.callListeners (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\sequential_executor.js:115:18)
    at Request.emit (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\request.js:682:14)
    at Request.transition (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\xampp\htdocs\node-fw\node_modules\aws-sdk\lib\state_machine.js:26:10
``` 

If you have any tip, it'd be greatly appreciated!

**Comment by nspragg** [comment]
How long do you messages typically take to process?

**Comment by 26medias** [comment]
Just a few ms, always less than 1sec.

However that only happen locally, not on the server, so I suspect it might be due to my local server rebooting regularly when I try new code (nodemon), while an item was processing in the queue. In that case the callback wouldn't be called due to the process being interrupted.
If that's the case, it's a non-issue.

I'll update if I confirm.

Thanks.

**Comment by nspragg** [comment]
This does not seem to be an issue with sqs-consumer, so closing for now. However, I'm happy to re-open if you find evidence to suggestion it's this library.

**Comment by 26medias** [comment]
Why is the library throwing an exception in that case instead of just skipping over the expired item and continuing?

**Comment by adb** [comment]
I'm seeing the same issue. It's a race condition, in that the message has expired while we were processing it, but sqs-consumer is still trying to delete it. It seems like sqs-consumer should be catching the error in this case, since a message expiring before we can delete it is not actually a problem.

**Comment by seantcanavan** [comment]
@adb The message can expire in two different ways however. One expiry will remove it from the queue and the other a `visibility timeout` which means just that specific consumer is the only one who can see the message in the queue. 

These `visibility timeouts` prevent the scenario where multiple consumers pull down the same message.

So it's not as simple as the message expiring in that it's gone from the queue. It's just that the specific handle the consumer had to the message is no longer valid.

At least that's my understanding of the problem.

https://stackoverflow.com/questions/46640779/deleting-message-from-sqs-fifo-queue-the-receipt-handle-has-expired
