### ISSUE TITLE
What if some message take very long time to consume?

### ISSUE THREAD

**Issue by wong2** [bbc/sqs-consumer#86]
I'm using the batchSize option (set to 10), consume times vary for diffierent messages (for example, a user with 5 followers VS one with 10k followers), and now sqs-consumer will wait for the slowest one to complete before next poll

**Comment by jpaljasma** [comment]
If your workload is unpredictable, then one solution is to run multiple consumers in parallel (with smaller batchSize), either in-process or separate. I just tested this solution with Cluster, and it works great handling queue items in parallel.

**Comment by jbreckman** [comment]
@wong2 there actually is a more serious problem with this package around `visibilityTimeout`.  If you have 3 consumers on separate node instances and a 30 second visibility timeout, one consumer will wake up and start the work.  After 30 seconds the message will appear back in the queue and a quiet consumer will wake up and start doing the work while the first consumer is still working.

I fixed this last night and opened a PR for it.  Feel free to check out my branch of the project.

**Comment by wong2** [comment]
@jbreckman I think that's because the previous work isnt termanited after the `visibilityTimeout`?

**Comment by nspragg** [comment]
@jpaljasma - thanks for your suggestion. We don't use cluster but sounds like a reasonable suggestion. 

@wong2 - if you require a higher volume consumer, I suggest you investigate the use of this library:
https://github.com/TechnologyAdvice/Squiss
