### ISSUE TITLE
Question about Consumer.create with batchSize > 1 

### ISSUE THREAD

**Issue by 26medias** [bbc/sqs-consumer#88]
Hi,

When using Consumer.create() with batchSize > 1, should the callback be executed once when all the messages have been handled, or once per message in the batch?

I have some messages stuck in flight since I activated the batchSize > 1, and I can't figure out how to avoid that.

Thanks.

**Comment by simplepath** [comment]
I'm working on the same thing right now.  Is there a way to know that a batch is complete so that I can do some processing prior to done();

**Comment by tamal-appsbee** [comment]
@robinjmurphy is there any way to skip() like done() if want to skip for now to process it later when batch size is 1?

**Comment by jessegranger** [comment]
I just opened a pull request #92 to add a "response_processed" event, so you can do end-of-batch cleanup if needed.

To answer the original question, handleMessage() is called once per message, afaik there is currently no event or function call that is once per batch.
