### ISSUE TITLE
Make deleteMessage configurable?

### ISSUE THREAD

**Issue by mhussain** [bbc/sqs-consumer#93]
Hey! 

Is there any way to make deleting a message configurable? The scenario is that I want to delete a message when I know for sure I have processed it. 

Cheers.

**Comment by enmaso** [comment]
mhussain,

done() <-- deletes message from queue
done(err) <-- puts it back in queue

The caveat is that you need to set terminateVisibilityTimeout to true, which basically tells sqs-consumer that on error [done(err)] to "changeMessageVisibility" to 0.

**Comment by mhussain** [comment]
:+1: I will definitely test it out. Thanks.
