### ISSUE TITLE
Process more than 10 messages in parallel

### ISSUE THREAD

**Issue by faisalpathan** [bbc/sqs-consumer#96]
By default messages are processed one at a time – a new message won't be received until the first one has been processed. To process messages in parallel, use the batchSize option detailed below.
Can batchSize runs the different messages simultaneously at the same time and thus fetch remaining messages if any from the AWS SQS and then execute them as well or we have to apply parent and child process for parallel execution of multiple messages from the aws SQS

**Comment by akashsaluja** [comment]
Have you found out for sure? Anyway the if messages are polled in batch, they will be processed in parallel in the same way a http request is processed in parallel. Please share your views as well.

**Comment by DiegoRBaquero** [comment]
They are processed in parallel, but polling won't happen until all those are fully processed.

**Comment by guyisra** [comment]
Would it be possible to run several consumers with batchSize of 10 to get more concurrency? Or would SQS limit the requests per host?

**Comment by akashsaluja** [comment]
@guyisra Why would you want to run multiple consumers, you can just increase the batch size.

**Comment by guyisra** [comment]
@akashsaluja batchSize limit is 10, so can't process more than 10 message in a single consumer

**Comment by akashsaluja** [comment]
@guyisra My apologies if that's the case. Interested to know the way then.

**Comment by guyisra** [comment]
@akashsaluja this has an example on how it could be done (https://github.com/bbc/sqs-consumer/issues/51) 

Basically, create as many consumers as needs, with a loop

**Comment by niklasR** [comment]
Polling more than 10 messages at a time is a limitation of the system. We like to keep this library quite lean and not complicate this unnecessarily. 
@guyisra has pointed out a workaround, so I'll close this issue for now.
